#+title: Infra Manual
#+description: CC Infrastructure Manual
#+property: header-args :dir /home/ellis/comp/infra/
#+property: header-args:dot :dir /tmp/ :file bootstrap.svg
#+setupfile: ../../clean.theme
#+infojs_opt: toc:nil home:https://compiler.company up:./ view:overview
#+property: header-args :eval no-export* Overview

This manual is intended for developers of the [[vc:core][core]] software suite. The
core is a Lisp development system which is designed for a very
specific type of user, and the [[vc:infra][infra]] project is designed to fully
provision machines for these users or *operators* as we will refer to
them.

* Introduction
:PROPERTIES:
:ID:       12988dd2-3367-4a11-aec5-c6fed1539cbc
:CREATED:  <2025-11-05 Wed 19:35>
:END:

*As a rule we only support x86_64 Arch Linux operator machines* - we
may support other targets for specific purposes but when talking about
an *operator machine* we are refering specifically to the x86_64
arch linux build with all of our libraries as well as the core
itself. There is no guarantee that the core software suite will
function correctly outside of this specific build, although if you
disable enough features it eventually will to a limited degree
depending on how well-provisioned your machine is. Other targets are
only tested or shipped as needed internally.

* Overview
:PROPERTIES:
:ID:       2015b333-bc24-40ea-b9ad-2f514b57b83b
:CREATED:  <2025-11-05 Wed 20:07>
:END:
The project skelfile pulls in our utilities from =util.lisp= in the
project root and contains a long list of rules which use the files in
the =scripts= directory. These rules are called via the =skel= cli
tool to build all of our dependencies from source, package them, and
send them to the =packy=.

There are several sub-projects inside infra:
- home :: user home directory management (similar to GNU stash)
- pod :: Podman-based containers - two base images (=o0= and =w0=)
  provision the containerfile definitions in the project skelfile
- box :: QEMU/bare-metal images, currently based on [[id:06ee60a3-9a98-40d2-893b-39ce992fc0dc][Archiso]].

** Requirements
:PROPERTIES:
:ID:       488e4c5b-be7f-4f1c-b713-4948965717c2
:CREATED:  <2025-11-05 Wed 19:39>
:END:
- *Host Requirements*
  - x86_64 >4 core CPU
  - 8G RAM
  - 32G Disk Space
  - Linux kernel
- *Minimum Dependencies*
  - mercurial
  - git
  - zstd
  - openssl

* Getting Started
:PROPERTIES:
:ID:       0d5496f3-3bba-4a90-ad83-708421df0b21
:CREATED:  <2025-11-05 Wed 20:16>
:END:
- NOTE :: as of [2025-11-05 Wed] the containers and disk images are \\
  not hosted publicly so send me a message if you'd like to \\
  investigate.

** Containers
:PROPERTIES:
:ID:       88d4e10b-2c7f-466f-ad7e-9a7ca7b018c9
:CREATED:  <2025-11-05 Wed 20:32>
:END:
The easiest way to get started is by downloading one of the Podman
container images. The default operator container has root privileges
and the worker containers have a minimal configuration and limited
privileges.

** Disk Images
:PROPERTIES:
:ID:       a5fd3b7a-c5e1-4a0e-87b4-b7b12d2450e3
:CREATED:  <2025-11-05 Wed 20:32>
:END:
The next step towards enlightenment is to download one of the disk
images and run it in QEMU. If you're feeling particularly brave you
now have all you need to boot into the core environment directly from
disk :).

A core installer is planned for next year which will provide an
interface for customizing the installation with user profiles and
settings.

** Bootstrap
:PROPERTIES:
:ID:       ac3b0505-996d-4526-89f2-aad372d6cff7
:CREATED:  <2025-11-05 Wed 20:35>
:END:
Bootstrapping here is defined as the process which gets us from a
vanilla, unprovisioned machine to a *fully functional core*. Note that
bootstrapping does not get us to a full *operator machine*, instead it
provisions the machine enough so that you have the capability to
transition to a full operator if you choose to do so.

As of [2025-11-05 Wed] the bootstrap process is unfortunately limited
to the pod container rules. Will eventually be provided in a PKGFILE.
