#+title: Infra Manual
#+description: CC Infrastructure Manual
#+property: header-args :dir /home/ellis/comp/infra/
#+property: header-args:dot :dir /tmp/ :file bootstrap.svg
#+setupfile: ../../clean.theme
#+infojs_opt: toc:nil home:https://compiler.company up:./ view:overview
#+property: header-args :eval no-export* Overview

This manual is intended for developers of the [[vc:core][core]] software suite. The
[[vc:infra][infra]] project is designed to fully provision machines for *operators*
in our ecosystem.

* Introduction
:PROPERTIES:
:ID:       12988dd2-3367-4a11-aec5-c6fed1539cbc
:CREATED:  <2025-11-05 Wed 19:35>
:END:
This manual is written for x86_64 systems, but accounts for Intel vs
AMD CPU optimizations.

We may support other targets for specific purposes but when talking
about an *operator machine* we are refering specifically to the x86_64
arch linux build with all of our libraries as well as the core
itself. There is no guarantee that the core software suite will
function correctly outside of this specific build.

* Overview
:PROPERTIES:
:ID:       2015b333-bc24-40ea-b9ad-2f514b57b83b
:CREATED:  <2025-11-05 Wed 20:07>
:END:
The project [[vc:infra/file/tip/skelfile][skelfile]] pulls in our utilities from [[vc:infra/file/tip/util.lisp][util.lisp]] in the
project root and contains a long list of rules which use the files in
the [[vc:infra/file/tip/scripts/][scripts]] directory. These rules are called via the =skel= cli tool
to build all of our dependencies from source, package, and deploy
them.

There are several sub-projects inside infra:
- [[vc:infra/home][home]] :: home directory management
- [[vc:infra/pod][pod]] :: [[id:89199dcd-fabd-4952-b5e9-1b3ffaf06e6b][Podman]] containers
- [[vc:infra/box][box]] :: [[id:06ee60a3-9a98-40d2-893b-39ce992fc0dc][Archiso]] and [[id:c4f26ef4-a936-4cf3-8218-4d23dbd9b33a][QEMU]] configs

** Requirements
:PROPERTIES:
:ID:       488e4c5b-be7f-4f1c-b713-4948965717c2
:CREATED:  <2025-11-05 Wed 19:39>
:END:
- *Host Requirements*
  - x86_64
  - 8G RAM
  - 32G Disk Space
  - Linux kernel
- *Minimum Dependencies*
  - mercurial
  - git
  - zstd
  - openssl

* Getting Started
:PROPERTIES:
:ID:       0d5496f3-3bba-4a90-ad83-708421df0b21
:CREATED:  <2025-11-05 Wed 20:16>
:END:
** Containers
:PROPERTIES:
:ID:       88d4e10b-2c7f-466f-ad7e-9a7ca7b018c9
:CREATED:  <2025-11-05 Wed 20:32>
:END:
The easiest way to get started is by downloading one of the Podman
container images. The default operator container has root privileges
and the worker containers have a minimal configuration and limited
privileges.

** ISOs
:PROPERTIES:
:ID:       a5fd3b7a-c5e1-4a0e-87b4-b7b12d2450e3
:CREATED:  <2025-11-05 Wed 20:32>
:END:

** Bootstrap
:PROPERTIES:
:ID:       ac3b0505-996d-4526-89f2-aad372d6cff7
:CREATED:  <2025-11-05 Wed 20:35>
:END:
Bootstrapping here is defined as the process which gets us from a
vanilla, unprovisioned machine to an *operator machine* from scratch.
