#+title: Infra Manual
#+description: CC Infrastructure Manual
#+property: header-args :dir /home/ellis/comp/infra/
#+property: header-args:dot :dir /tmp/ :file bootstrap.svg
#+setupfile: ../../clean.theme
#+infojs_opt: toc:nil home:https://compiler.company up:./ view:overview
#+property: header-args :eval no-export

* Overview
This manual is intended for developers of the [[vc:core][core]] software suite. The
[[vc:infra][infra]] project is designed to fully provision machines for *operators*
in our ecosystem.

* Introduction
:PROPERTIES:
:ID:       12988dd2-3367-4a11-aec5-c6fed1539cbc
:CREATED:  <2025-11-05 Wed 19:35>
:END:
This manual is written for [[id:4c7530b8-6d6f-475a-b2a3-986a10a0d812][x86_64]] systems, but accounts for [[id:4555306b-b68c-43a9-8a54-e4066ca7437d][Intel]] vs
[[id:e2368655-59e9-404b-9ac6-cecb35216c11][AMD]] CPU optimizations.

We may support other targets for specific purposes but when talking
about an *operator machine* we are refering specifically to the
~x86_64~ core linux build with all of our libraries
pre-installed. There is no guarantee that the core software suite will
function correctly outside of our environment.

* Overview
:PROPERTIES:
:ID:       2015b333-bc24-40ea-b9ad-2f514b57b83b
:CREATED:  <2025-11-05 Wed 20:07>
:END:
The project [[vc:infra:skelfile][skelfile]] pulls in our utilities from [[vc:infra:util.lisp][util.lisp]] in the
project root and contains a long list of rules which use the files in
the [[vc:infra:scripts][scripts]] directory. These rules are called via the =skel= cli tool
to build all of our dependencies from source, package, and deploy
them.

There are several sub-projects inside infra:
- [[vc:infra/home][home]] :: home directory management
- [[vc:infra/pod][pod]] :: [[id:89199dcd-fabd-4952-b5e9-1b3ffaf06e6b][Podman]] containers
- [[vc:infra/box][box]] :: [[id:06ee60a3-9a98-40d2-893b-39ce992fc0dc][Archiso]] and [[id:c4f26ef4-a936-4cf3-8218-4d23dbd9b33a][QEMU]] configs

** Requirements
:PROPERTIES:
:ID:       488e4c5b-be7f-4f1c-b713-4948965717c2
:CREATED:  <2025-11-05 Wed 19:39>
:END:
- *Host Requirements*
  - x86_64
  - 8G RAM
  - 32G Disk Space
  - Linux kernel
- *Minimum Dependencies*
  - mercurial
  - git
  - zstd
  - openssl

* Getting Started
:PROPERTIES:
:ID:       0d5496f3-3bba-4a90-ad83-708421df0b21
:CREATED:  <2025-11-05 Wed 20:16>
:END:
** TODO Containers
:PROPERTIES:
:ID:       88d4e10b-2c7f-466f-ad7e-9a7ca7b018c9
:CREATED:  <2025-11-05 Wed 20:32>
:END:
:LOGBOOK:
- State "TODO"       from              [2026-05-09 Sat 22:09]
:END:
Several containers are hosted publicly and can be retrieved using
=podman import=:
#+begin_src shell
podman import https://packy.compiler.company/pod/op.tar.zst
#+end_src

#+RESULTS:
: Downloading from "https://packy.compiler.company/pod/op.tar.zst"

** TODO Packs
:PROPERTIES:
:ID:       ac3b0505-996d-4526-89f2-aad372d6cff7
:CREATED:  <2025-11-05 Wed 20:35>
:END:
:LOGBOOK:
- State "TODO"       from              [2026-05-09 Sat 22:46]
:END:
We maintain our own package archive which is compatible with the [[id:03215632-83da-48c0-9f36-df72a9e956b5][Arch
Build System]] and [[id:3c814d4d-8635-4c6f-a849-5c7d72db20fe][Pacman]]. you may install packages using =hg clone= and
=makepkg= or by adding as a custom package repository to
=/etc/pacman.conf=:

#+begin_example
[packy]
SigLevel = Optional
Server = https://packy.compiler.company
#+end_example

Make sure to download and add our [[packy:data/rwest.gpg][GPG key]] to verify signed packages:
#+begin_src shell
curl https://packy.compiler.company/data/rwest.gpg -o /tmp/rwest.gpg
sudo pacman-key --add /tmp/rwest.gpg
sudo pacman-key --finger 196FA2C31A5821D0
#+end_src

#+RESULTS:

- pacman install
  #+begin_src shell
  pacman -Sy core
  #+end_src

  #+RESULTS:

- makepkg install
  #+begin_src shell
  hg clone https://vc.compiler.company/packy/core
  cd core
  makepkg -si
  #+end_src

  #+RESULTS:
