#+title: infra/quickstart
#+author: Richard Westhaver
#+email: ellis@rwest.io
#+description: Infra Quickstart Guide
#+property: header-args :dir /home/ellis/comp/infra/
#+setupfile: ../../clean.theme
The CC =infra= project is the CC software deployment toolkit.

- *Host Requirements*
  - x86_64 4 core CPU
  - 8G RAM
  - 32G Disk Space
  - Linux kernel

- *Minimum Dependencies*
  - mercurial
  - git
  - zstd

* TODO check.sh
Check that the current host is a qualified builder.

This will interrogate the system, checking for minimum
requirements. If any requirement isn't met an error is
signaled. Environment variables are also reported here, but not
set. On completion, the file =host.sxp= is written to the current
directory.

The minimum software dependencies above should be installed via your
system's package manager. The remaining dependencies are installed via
the =install.sh= script.

#+begin_src shell
./check.sh
#+end_src

#+RESULTS:
| STASH=          |
| STORE=          |
| DIST=           |
| PACKY_URL=      |
| VC_URL=         |
| INSTALL_PREFIX= |
| CC=             |
| AR=             |
| HG=             |
| GIT=            |
| LISP=           |
| RUST=           |
| LD=             |
| SHELL=/bin/bash |
| DEV=            |
| DEV_HOME=       |
| ID=             |
| WORKER=         |
| WORKER_ID=      |
| WORKER_HOME=    |
| CARGO_HOME=     |
| RUSTUP_HOME=    |

* TODO bootstrap.sh
Bootstrap the core.

- download and prepare target-specific dependencies
- install the latest =sk= binary from https://packy.compiler.company
  to the stash
- compile and load =bootstrap.lisp=

Upon completion a local =stash= directory is provisioned. At this
point we no longer need to depend on shell scripting as we have a
fully interactive Lisp environment to hack on our builds with.

From here, you may run =skel inspect= to inspect the infra =skelfile=
and select a target to build on your machine or in a container. Use
=skel --help= for a list of other commands.

* TODO deploy.lisp
Deploy =infra= builds to a remote.

Deployment involves 'packing' a target found in =stash=, archiving it,
compressing it, and sending it to a remote location possibly with a
signature, checksum, or other metadata, and possibly encrypted. A
'package' may also be a raw directory of plain-text files. It's a very
loose term. Where the package ends up and how it is packed depends on
the build-config and skelfile slots.

Production deployments end up at https://packy.compiler.company.


* TODO install.lisp
Install core packages locally.
