#+title: Core User Manual
#+author: Richard Westhaver
#+email: ellis@rwest.io
#+property: header-args :dir ~/comp/core/ :eval no-export
#+setupfile: ../../clean.theme
#+texinfo_filename: core.info
#+texinfo_dir_category: Software development
#+texinfo_dir_title: Core: (core)
#+texinfo_dir_desc: CC Software Development Ecosystem

This manual documents the [[comp:][CC]] [[vc:core][core]] software suite. It is intended for
users/developers and assumes a intermediate level understanding of
computer programming concepts such as OOP, FP, IDEs, and the
shell. 

The core is a Lisp development system used to build next-gen
applications. It is composed of interconnected modules providing an
exceptionally powerful development ecosystem.

* Introduction
:PROPERTIES:
:ID:       156ffb70-9e00-4532-be47-b921c1825a91
:END:
Welcome to the *core*, the primary software development ecosystem of
[[comp:][CC]].

The core provides the foundation of all applications we produce. It is
optimized for rapid development of next-gen applications.

The core is highly opinionated - and these opinions are consistently
hard-coded into our development practices.

For example:
- *Linux is the only platform worth supporting*
  - We make no efforts to support cross-compilation or porting of our
    software to devices or operating systems the developer can't fully
    control such as Windows/MacOS/iOS/Android. We always assume the
    developer is running a GNU/Linux host.
- *Portability is over-rated*
  - CL implementations (lisps) share a base language but many
    parts of the ANSI CL spec are left up to interpretation: threads,
    OS, GC, MOP, etc
  - Many lisp packages attempt to account for as many lisps as
    possible via conditional compilation and wrappers - this clutters
    up the code base, is difficult to test, and is error-prone.
  - Instead of accounting for multiple compilers, we realize that we
    only need one - SBCL currently. The core does not contain any
    support for alternate lisps.
  - 'One true lisp' is all we need, and we're only concerned with
    /internal/ consistency - we are never bound by the choices in
    implementation made by other lisps (although there is much to
    learn from them).
- *Introspection is under-rated*
  - Black boxes (proprietary codes) are disrespectful to
    developers. Computer systems should be transparent by nature and
    make minimal efforts to 'hide' internal representations of data
    and code.
  - Never hide a part of the system, unless you have a very good
    reason for doing so.
- *Follow the Bleeding Edge*
  - We pull and rebuild the latest changes for all of our dependencies
    frequently
  - We host mirrors of all our major dependencies
  - Core development is always based on latest changes, can optionally
    downgrade for release builds where stability is valued
  - incorporate pre-release APIs and our own custom patches as needed.

* Overview
:PROPERTIES:
:ID:       ceb67759-c656-411d-a0c0-df19b18732e5
:END:
The core itself is not an application but is complex enough that it
merits its own dedicated manual. There are dedicated manuals for the
[[file:app/][applications]] and [[file:lib][libraries]] which are part of the core, so what we are
concerned with here is exploring, managing, and hacking on the source
code itself.

This manual is often technical, but occassionally theoretical in
nature and intended for software developers with expertise in Lisp,
GNU/Linux, and Emacs.

The Core is a Lisp system. Common Lisp is our language of choice and
there is a significant amount of Emacs Lisp code too. The only other
language present at this time is C (0.1%).

** Source Code
:PROPERTIES:
:ID:       66163a74-dc41-4679-bf83-a2c7598bb316
:CREATED:  <2025-06-02 Mon 20:54>
:END:
#+begin_src sh :eval no-export
  ls
#+end_src

#+RESULTS:
| alien      |
| bin        |
| core.lisp  |
| core.sys   |
| etc        |
| ironclad   |
| lib        |
| ppcre      |
| readme.org |
| skel       |
| skelfile   |
| std        |

- Common Lisp \\
  The =STD= library lives under the =std= directory, FFI libraries
  such as =ROCKSDB= under the =ffi= directory and user libraries like
  =RDB= under the =lib= directory. Executables and scripts are located
  under =bin=, application code for the =SKEL= and =MPK= systems under
  =app= and various benchmarks under =bench=.
  
  The =app= directory contains 
- Emacs Lisp \\
  The =emacs= directory contains a complete Emacs Lisp configuration
  which is used during development.

** Images
:PROPERTIES:
:ID:       346fbc32-b1d2-489b-9091-3767ba372281
:CREATED:  <2025-06-02 Mon 20:35>
:END:
*Images* refer to the binary file resulting from a call to
 =SAVE-LISP-AND-DIE=. According to SBCL this file contains:

#+begin_quote
enough information to restart a Lisp process later in the same state,
in the file of the specified name.
#+end_quote

See the function docs for details - there are many options available
which determine how the image can be used directly or dynamically from
other programs.

The =core images= we produce are executables which contain the full
SBCL runtime at their disposal. Note that these images can be quite
large - multiple gigabytes in some cases, and so care should be taken
when enabling additional build-time features.

Note that image-based development is quite unique. You start inside
your Lisp implementation's core image which contains the Lisp runtime
in its executable. The runtime in SBCL is compiled C code which you
may be included with the images you save to make them executable, or
you can remove it to save space. Restarting an image in the /exact
same state/ you saved it in is as simple as executing sbcl with the
=--core= argument or executing the saved core file (with runtime)
directly.

The development experience is exceptionally fluid when fully
appreciated. You have everything at your fingertips, always fully
compiled and ready to load into memory at a moment's notice.

Images are concatenative - they always build on an existing image. We
start with the ANSI LISP 'kernel' image, then we save it, extend it,
and repeat indefinitely. The natural evolution of this concept is to
have your *entire system in a Lisp image*. It is a 'maximalist'
philosophy which is deeply ingrained into the very idea of Lisp,
although ultimately relegated to the long-forgotten Lisp Machines.

Image-based development does come with its own set of foot guns - it
is more complex by nature and easy to end up in an unusable state when
you compile in faulty code. However the biggest conflict that arises
from images is that they are *anti-UNIX*.

GNU/Linux distributions today come with hundreds of binaries. The vast
majority of these are single-use tools with simple text interfaces
which aide themselves to composability via the shell. Lisp images are
not single-use tools - they always contain a complete Lisp runtime in
addition to any extensions you've added - so if you want to use them
like UNIX binaries with one image per application or tool, you're
duplicating a tremendous amount of code in each image[fn:1].

One of the goals of the =core= is to realize a full appreciation of
images and image-based development, starting from GNU/Linux Userspace
and working our way towards service management and then the
kernel. The general strategy is to reduce the OS environment while
extending our Lisp image. We aim to first serve as a default user
login shell, and ultimately challenge SystemD for PID1. If we are
successful, we will have a complete Lisp system compatible with the
Linux kernel.

[fn:1] Some Lisp applications developers do actually prefer this -
taking GNU/Linux and the UNIX philosophy as a constant in any
self-respecting OS.

* Getting Started
:PROPERTIES:
:ID:       636ffa98-c39a-4f2a-9a49-aa82497a8ca8
:END:
** Bootstrap
:PROPERTIES:
:ID:       dcb3ffff-5388-4387-8a46-553ae0309d70
:END:
Bootstrapping the core can be done via an existing core image or the
=skel= binary in a 'self-bootstrapping' fashion. See the [[comp:docs/infra][infra]] project
documentation for details on that process.

Bootstrapping from SBCL is quite easy too. All that is needed is to
get the source, load the project =skelfile= and run =sk-make=.

  #+begin_src shell :eval never :exports code
    # clone the source code from a mirror
    git clone https://codeberg.org/c-c/core
    cd core
    sbcl
  #+end_src

Then in the SBCL REPL:
#+begin_src lisp :dir ~/comp/core/ :exports both :eval never
  (ql:quickload :skel)
  (in-package :sk-user)
  (init-skel)
  (sk-make *skel-project* :all)
#+end_src

#+RESULTS:
| :ALL |

Installation can be done from the same REPL session. By default the
=core= binary will be written to =/usr/local/bin/= and a series of
symlinks will be created in the same directory - similar to Busybox
binaries. Note that this may not work in a =SLIME= repl since =sudo=
is called and might need input at the terminal.

#+begin_src lisp :dir ~/comp/core/ :package sk-user :eval never :exports code
  (sk-make *skel-project* :install-core)
#+end_src

You should see some output like the following:

#+begin_example
skel -> core -> /usr/local/bin/
homer -> core -> /usr/local/bin/
packy -> core -> /usr/local/bin/
rdb -> core -> /usr/local/bin/
organ -> core -> /usr/local/bin/
vc -> core -> /usr/local/bin/
gen -> core -> /usr/local/bin/
swm -> core -> /usr/local/bin/
#+end_example

*** Dependencies
:PROPERTIES:
:ID:       22b763b9-c781-4061-b5ef-fc4f19720cf0
:END:
If you do choose to build from source without using =infra=, make sure
you're on GNU/Linux and have the required packages installed.

- *Required*
  - linux-headers
  - gcc
  - sbcl
  - emacs
  - quicklisp
  - rocksdb
  - zstd
  - mercurial
  - openssl

- /Optional/
  - cuda
  - evdev
  - jack
  - libjpeg-turbo
  - xkbcommon
  - ublksrv
  - keyutils
  - wasmer
  - sndfile
  - libssh2
  - btrfsutils
  - podman
  - qemu
  - gstreamer
  - rustls
  - tree-sitter
  - blake3
  - liburing
  - alsa
  - ffmpeg
  - glib
  - chromaprint
  - openblas (blas/lapack)
** Configuration
:PROPERTIES:
:ID:       d9a1f958-c43e-4465-9916-3526f7a27268
:END:
The next thing you'll want to take care of is user configuration.

The only /required/ development dependency which needs configuring is
Emacs.
*** Core
:PROPERTIES:
:ID:       db2ee1f1-846f-433c-9747-83ec18d47e40
:END:
The core is a single binary which dispatches on argv[0] from the
CLI. Each unique symlink to the core binary is treated as a separate
dispatch to a 'main' function like so:

#+begin_src lisp :exports code :eval never
  (define-multi-main dispatch-core
    (progn (in-package :core-lisp)
           ,#+nil ...)
    (:skel (bin/skel::start-skel))
    (:homer (bin/homer::start-homer))
    (:mpk (bin/mpk::start-mpk))
    ,#+nil ...)
#+end_src

The default path (when argv[0]=core) accepts a lisp file as
configuration just like =~/.sbclrc=, =corerc= respected the
=XDG_CONFIG_HOME= variable though and may be located in
=~/.config/corerc=.

The current apps that read a configuration file on startup are:
- skel - project management: =skelrc=
- homer - home management: =homerc=
- mpk - media production kit: =mpkrc=

By default they are located under =XDG_CONFIG_HOME=.

These apps all use the same /configuration object protocol/ from the
=OBJ/CONFIG= package and are printed to various S-Expression. Most
commonly the 'pretty' format is used which is simply a plist with
implied outer parentheses:

#+begin_src lisp :eval never
  :key1 val1
  :key2 val2
#+end_src

Canonically that would be:
#+begin_src lisp :eval never
  (:key1 val1
   :key2 val2)
#+end_src

*** Emacs
:PROPERTIES:
:ID:       6c87dbd0-0a4b-4395-bc70-fff94b680787
:END:
If you don't have your own Emacs config you can install the default CC
Emacs configuration using the =skel= command. 

- Warning :: this will overwrite files in your =.emacs= directory (defaults to =$XDG_CONFIG_HOME/emacs/=:
  #+begin_src shell :dir ~/comp/core/ :results output :exports both
  skel make install-emacs
  #+end_src

  #+RESULTS:
  : #:debug 0.105999
  : ; (#<rule install-emacs>)

The default config supports user customizations in a file with the
same name as the current user, so when the current =$USER= is ~ellis~
then we check for the file =ellis.el= and load it if it exists.

** Demo
:PROPERTIES:
:ID:       ec5dca14-eb23-4dac-962a-34f1a5d4fd1f
:CREATED:  <2025-07-07 Mon 14:11>
:END:
Core demo applications, examples, and tutorials can be found in the
[[gh:richardwesthaver/demo][demo repository]] with documentation [[comp:docs/demo][here]].
** Testing
:PROPERTIES:
:ID:       c074e53b-846d-45ed-8ddc-70e559ed6f0c
:END:
Each module in the core contains its own test suite located in the
=tests.lisp= file or =tests= directory and isolated to its own ASDF
system. The ASDF system is always the module name prefixed by
=/tests= - for example the =IO/TESTS= system is responsible for
testing the =IO= module system.

In addition to the test suite we have a set of experimental
benchmarks. These are kept in the top-level =bench= directory.

*** Regression Tests
:PROPERTIES:
:ID:       74af2f86-9025-44c8-83de-d41816d623bf
:CREATED:  <2025-06-02 Mon 18:26>
:END:
Testing the core can be done from the CLI using =skel=:

#+begin_src sh :dir ~/comp/core/ :eval never
  # skel compile tests
  skel run tests
#+end_src

or from lisp:

#+begin_src lisp :eval never
  (ql:quickload :core/tests)
  (rt:run-all-tests)
#+end_src

*** Benchmarks
:PROPERTIES:
:ID:       d2b45403-cec0-4b17-9295-d2ae7f19a1df
:CREATED:  <2025-06-02 Mon 18:26>
:END:

using =skel=:

#+begin_src sh :dir ~/comp/core/ :eval never
  # skel compile bench
  skel run bench db-stress
#+end_src

or from lisp:

#+begin_src lisp :eval never
  (ql:quickload :core/bench)
  (use-package :core/bench)
  (run-benchmark :db-stress)
#+end_src

#+RESULTS:
: #<PACKAGE "CORE/BENCH/DB/STRESS">

** Documentation
:PROPERTIES:
:ID:       2634e0bd-29b2-4191-9892-766abfa7435e
:CREATED:  <2025-09-30 Tue 21:48>
:END:
User docs for each [[file:app/][application]] and [[file:lib][library]] is available under separate
directories.
** Contributing
:PROPERTIES:
:ID:       e0657c76-395c-47b5-b5a6-1dcebd59ce7c
:CREATED:  <2025-06-02 Mon 19:36>
:END:
The core is currently a solo project and I don't plan on accepting
contributions in the near future. The core is its own private island,
isolated from the rest of the Common Lisp ecosystem and in almost all
cases contributions would be better directed towards other packages.

See [[https://awesome-cl.com/][Awesome CL]] for a list of projects which could use additional
support, and take note the comments scattered throughout the core
source code which often reference popular packages from the ecosystem.
* Concepts
:PROPERTIES:
:ID:       8e379ae7-5eca-4ccb-8603-e32a20ef2d37
:CREATED:  <2025-09-30 Tue 21:49>
:END:
** ULang
:PROPERTIES:
:ID:       17f9cf38-c7a3-42f7-9b48-58c9999d1b71
:CREATED:  <2025-09-30 Tue 21:49>
:END:
*** Babel
:PROPERTIES:
:ID:       5dacc810-e6c2-49c3-ba62-c85f536c44e4
:CREATED:  <2025-09-30 Tue 21:49>
:END:
*** Style
:PROPERTIES:
:ID:       63185a8a-cd68-4697-b5c8-eaa49eff514e
:CREATED:  <2025-09-30 Tue 21:51>
:END:
*** Workflows
:PROPERTIES:
:ID:       0fdb6ac8-baa0-4130-9ce2-c0fc38b38475
:CREATED:  <2025-09-30 Tue 21:51>
:END:
*** Glossary
:PROPERTIES:
:ID:       9e9b92ed-4ae7-4253-b41c-b1a862c9a538
:CREATED:  <2025-09-30 Tue 21:52>
:END:
** Lisp
:PROPERTIES:
:ID:       da4bc7cd-8b7f-4969-9dd5-a0c10a5c41b0
:CREATED:  <2025-09-30 Tue 21:50>
:END:
*** Macros
:PROPERTIES:
:ID:       1fdb7040-d003-4734-b3d3-7453782f8a63
:CREATED:  <2025-09-30 Tue 21:51>
:END:
*** Images
:PROPERTIES:
:ID:       0883806d-7660-4dba-8b23-1a9c43b303b3
:CREATED:  <2025-09-30 Tue 21:50>
:END:
*** Compilers
:PROPERTIES:
:ID:       861a913e-f575-4f7d-8664-b11ff4d43b8d
:CREATED:  <2025-09-30 Tue 21:50>
:END:
*** Modules
:PROPERTIES:
:ID:       f81af189-def0-4433-8da3-a9817a663245
:CREATED:  <2025-09-30 Tue 21:50>
:END:
*** DSLs
:PROPERTIES:
:ID:       b9f18978-82e5-46bd-a5f2-1aee430103bd
:CREATED:  <2025-09-30 Tue 21:53>
:AKA: Domain Specific Languages
:END:
**** Systems
:PROPERTIES:
:ID:       236ba44b-dd4a-4625-af74-cabfc208537b
:CREATED:  <2025-09-30 Tue 21:50>
:END:
** Control
:PROPERTIES:
:ID:       fe2c5b29-2953-4f45-ad05-64eb097f99b5
:CREATED:  <2025-09-30 Tue 21:54>
:END:
*** Source
:PROPERTIES:
:ID:       1ec074bf-4769-4cbf-91f8-95b2d32f0e1f
:CREATED:  <2025-09-30 Tue 21:54>
:END:
*** Compute
:PROPERTIES:
:ID:       cc8a17af-e01f-4004-98a3-546e3d2397ce
:CREATED:  <2025-09-30 Tue 21:54>
:END:
*** Data
:PROPERTIES:
:ID:       380fbb96-b625-4165-aea1-b9afdef0db0f
:CREATED:  <2025-09-30 Tue 21:54>
:END:
* Features
:PROPERTIES:
:ID:       06954eeb-7ed8-4a81-ae8b-730b4c89e40e
:CREATED:  <2025-09-30 Tue 21:55>
:END:
* Protocols
:PROPERTIES:
:ID:       bc25aea1-1375-405e-b091-6660e21e9916
:CREATED:  <2025-09-30 Tue 21:56>
:END:
* Applications
:PROPERTIES:
:ID:       01613601-0dc2-4d4d-9354-7ffcc0a1eaed
:CREATED:  <2025-09-30 Tue 21:58>
:END:
* Hacking
:PROPERTIES:
:ID:       a2797272-550f-4b96-a0c5-c0660af57d05
:CREATED:  <2025-09-30 Tue 21:56>
:END:
