#+title: Core User Manual
#+author: Richard Westhaver
#+email: ellis@rwest.io
#+property: header-args :dir ~/comp/core/
#+setupfile: ../../clean.theme
#+texinfo_filename: core.info
#+texinfo_dir_category: Software development
#+texinfo_dir_title: Core: (core)
#+texinfo_dir_desc: CC Software Development Ecosystem
This manual documents the [[comp:][CC]] [[vc:core][core]] software. The core is a
multi-language library and framework used to build advanced
applications. It is composed of language-specific collections of
interconnected libraries providing an exceptionally powerful
development ecosystem.

* Introduction
:PROPERTIES:
:ID:       156ffb70-9e00-4532-be47-b921c1825a91
:END:
Welcome to the core, the software development ecosystem of [[comp:][CC]].

The idea of a =core= is probably one that you are quite familiar with
as a developer of software. It implies something that is fundamental;
the 'machine behind the machine', whatever the machine may be.

The =core= is often the most important part of your application - the
one you want to get right. Where things get tricky is when you have
many different applications, all which have a =core=, which you
need to get right to avoid embarassment.

The natural evolution is to start abstracting away the commonalities
between your application core, refactoring them into a new project. As
your applications grow, you keep searching for common patterns and
refactoring. The circle of life goes on.

This is *not* how the CC core is developed. Our core does not inherit
from applications. It is not a 'top-down' system. Instead, it is built
'bottom-up' from scratch and kept insulated (but not completely
isolated) from applications.

This design decision is rooted in a philosophy which favors the
developer, or more specifically the /hacker/ over all other
stake-holders in our systems.

* Overview
:PROPERTIES:
:ID:       ceb67759-c656-411d-a0c0-df19b18732e5
:END:
