#+title: Core User Manual
#+author: Richard Westhaver
#+email: ellis@rwest.io
#+property: header-args :dir ~/comp/core/ :eval no-export
#+setupfile: ../../clean.theme
#+texinfo_filename: core.info
#+texinfo_dir_category: Software development
#+texinfo_dir_title: Core: (core)
#+texinfo_dir_desc: CC Software Development Ecosystem

This manual documents the [[comp:][CC]] [[vc:core][core]] software. The core is a Lisp
development system used to build next-gen applications. It is composed
of interconnected modules providing an exceptionally powerful
development ecosystem.

* Introduction
:PROPERTIES:
:ID:       156ffb70-9e00-4532-be47-b921c1825a91
:END:
Welcome to the *core*, the primary software development ecosystem of
[[comp:][CC]].

The core provides the foundation of all applications we produce. It is
optimized for rapid development of next-gen applications.

The core is highly opinionated - and these opinions are consistently
hard-coded into our development practices.

For example:
- *Linux is the only platform worth supporting*
  - We make no efforts to support cross-compilation or porting of our
    software to devices or operating systems the developer can't fully
    control such as Windows/MacOS/iOS/Android. We always assume the
    developer is running a GNU/Linux host.
- *Portability is over-rated*
  - CL implementations (lisps) share a base language but many
    parts of the ANSI CL spec are left up to interpretation: threads,
    OS, GC, MOP, etc
  - Many lisp packages attempt to account for as many lisps as
    possible via conditional compilation and wrappers - this clutters
    up the code base, is difficult to test, and is error-prone.
  - Instead of accounting for multiple compilers, we realize that we
    only need one - SBCL currently. The core does not contain any
    support for alternate lisps.
  - 'One true lisp' is all we need, and we're only concerned with
    /internal/ consistency - we are never bound by the choices in
    implementation made by other lisps (although there is much to
    learn from them).
- *Introspection is under-rated*
  - Black boxes (proprietary codes) are disrespectful to
    developers. Computer systems should be transparent by nature and
    make minimal efforts to 'hide' internal representations of data
    and code.
  - Never hide a part of the system, unless you have a very good
    reason for doing so.
- *Follow the Bleeding Edge*
  - We pull and rebuild the latest changes for all of our dependencies
    frequently
  - We host mirrors of all our major dependencies
  - Core development is always based on latest changes, can optionally
    downgrade for release builds where stability is valued
  - incorporate pre-release APIs and our own custom patches as needed.

* Overview
:PROPERTIES:
:ID:       ceb67759-c656-411d-a0c0-df19b18732e5
:END:
The core itself is not an application but is complex enough that it
merits its own dedicated manual. There are dedicated manuals for the
[[file:app/][applications]] and [[file:lib][libraries]] which are part of the core, so what we are
concerned with here is exploring, managing, and hacking on the source
code itself.

This manual is often technical, but occassionally theoretical in
nature and intended for software developers with expertise in Lisp,
GNU/Linux, and Emacs.

The Core is a Lisp system. Common Lisp is our language of choice and
there is a significant amount of Emacs Lisp code too. The only other
language present at this time is C (0.1%).

** Source Code
:PROPERTIES:
:ID:       66163a74-dc41-4679-bf83-a2c7598bb316
:CREATED:  <2025-06-02 Mon 20:54>
:END:
The source for each _module_ is located in its own directory. The
=STD= module lives under the =std/= directory, FFI modules such as
=ROCKSDB= under the =ffi/= directory and library modules like =RDB=
under the =lib/= directory. The top-level directory is dedicated to
the =CORE= module itself.

** Modules
:PROPERTIES:
:ID:       13a2689e-6d57-44b0-a8e0-fad145832871
:CREATED:  <2025-06-02 Mon 20:23>
:END:
*Core modules* loosely equate to a lisp system and its 'sub-systems' -
for example the ~CORE~ module contains the ~CORE~ system and
~CORE/TESTS~, ~CORE/USER~, etc sub-systems. They are effectively a
container of one or more systems. 

Developers may import ASDF systems provided by a module and use the
packages it contains, or use the compiled lisp /images/ directly.

A full module system is planned which leverages the =*MODULES*=
variable, in a similar fashion to ASDF with support for more direct
usage of modules in day-to-day programming.

** Features
:PROPERTIES:
:ID:       25ecd39d-e6ea-4e26-8818-438df27cd253
:CREATED:  <2025-06-02 Mon 19:55>
:END:
The core contains /many/ features which are included in the compiled
image by default. 

The following features have special meaning at _build-time_ where they
determine which modules get loaded into the resulting core image.

#+begin_src lisp :eval never
  :std     ; the STD library - always required
  :prelude ; the PRELUDE library - on by default
  :gui     ; the GUI module - optional
  :web     ; the WEB module - optional
  :full    ; ALL modules
#+end_src

The rest of the features provided by the core are also tracked in the
=*FEATURES*= list but should not need to be updated manually.

#+begin_src lisp :post transpose
  ,*features*
  ;; *ffi-features*
  ;; *core-features*
#+end_src

#+RESULTS:
| :KEYUTILS                       |
| :UBLKSRV                        |
| :SNDFILE                        |
| :SSH2                           |
| :XKBCOMMON                      |
| :TREE-SITTER-JSON               |
| :BTRFSUTIL                      |
| :BTRFS                          |
| :RUSTLS                         |
| :USER                           |
| :SWANK                          |
| :SKEL                           |
| :TREE-SITTER-RUST               |
| :TREE-SITTER-JAVASCRIPT         |
| :TREE-SITTER-C                  |
| :TREE-SITTER-ALIEN              |
| :TREE-SITTER                    |
| :CORE                           |
| :BLAKE3                         |
| :ROCKSDB                        |
| :RFC3912                        |
| :NET                            |
| :SPLIT-SEQUENCE                 |
| :BORDEAUX-THREADS               |
| :GLOBAL-VARS                    |
| :FLEXI-STREAMS                  |
| CFFI-FEATURES:FLAT-NAMESPACE    |
| CFFI-FEATURES:X86-64            |
| CFFI-FEATURES:UNIX              |
| :CFFI                           |
| CFFI-SYS::FLAT-NAMESPACE        |
| ALEXANDRIA::SEQUENCE-EMPTYP     |
| :IO                             |
| :KBD                            |
| :ZSTD                           |
| :URING                          |
| :RFC8141                        |
| :RFC6874                        |
| :RFC3986                        |
| :RFC3492                        |
| :IRONCLAD-ASSEMBLY              |
| :IRONCLAD-SB-VM-EA              |
| :IRONCLAD-FAST-MOD64-ARITHMETIC |
| :IRONCLAD-FAST-MOD32-ARITHMETIC |
| :STD                            |
| :NAMED-READTABLES               |
| :THREAD-SUPPORT                 |
| :CL-PPCRE                       |
| :CLI                            |
| :QUICKLISP                      |
| :ASDF3.3                        |
| :ASDF3.2                        |
| :ASDF3.1                        |
| :ASDF3                          |
| :ASDF2                          |
| :ASDF                           |
| :OS-UNIX                        |
| :NON-BASE-CHARS-EXIST-P         |
| :ASDF-UNICODE                   |
| :ARENA-ALLOCATOR                |
| :X86-64                         |
| :MARK-REGION-GC                 |
| :64-BIT                         |
| :ANSI-CL                        |
| :COMMON-LISP                    |
| :ELF                            |
| :IEEE-FLOATING-POINT            |
| :LINUX                          |
| :LITTLE-ENDIAN                  |
| :PACKAGE-LOCAL-NICKNAMES        |
| :SB-CORE-COMPRESSION            |
| :SB-LDB                         |
| :SB-PACKAGE-LOCKS               |
| :SB-THREAD                      |
| :SB-UNICODE                     |
| :SBCL                           |
| :UNIX                           |

** Images
:PROPERTIES:
:ID:       346fbc32-b1d2-489b-9091-3767ba372281
:CREATED:  <2025-06-02 Mon 20:35>
:END:
*Core Images* refer to the binary file resulting from a call to
 =SAVE-LISP-AND-DIE=. According to SBCL this file contains

#+begin_quote
enough information to restart a Lisp process later in the same state,
in the file of the specified name.
#+end_quote

See the function docs for details - there are many options available
which determine how the image can be used directly or dynamically from
other programs.

The images we produce are most often executable and contain the full
SBCL runtime at their disposal. Note that these images can be quite
large - multiple gigabytes in some cases, and so care should be taken
when enabling additional build-time features.

* Getting Started
:PROPERTIES:
:ID:       636ffa98-c39a-4f2a-9a49-aa82497a8ca8
:END:
*** Bootstrap
:PROPERTIES:
:ID:       dcb3ffff-5388-4387-8a46-553ae0309d70
:END:
Bootstrapping the core can be done via an existing core image or the
=skel= binary in a 'self-bootstrapping' fashion. See the [[comp:docs/infra][infra]] project
documentation for details on that process.

Bootstrapping from SBCL is quite easy too. All that is needed is to
get the source, load the project =skelfile= and run =sk-make=.

  #+begin_src shell :eval never :exports code
    # clone the source code from a mirror
    git clone https://codeberg.org/c-c/core
    cd core
    sbcl
  #+end_src

Then in the SBCL REPL:
#+begin_src lisp :dir ~/comp/core/ :exports both :eval never
  (ql:quickload :skel)
  (in-package :sk-user)
  (init-skel)
  (sk-make *skel-project* :all)
#+end_src

#+RESULTS:
| :ALL |

Installation can be done from the same REPL session. By default the
=core= binary will be written to =/usr/local/bin/= and a series of
symlinks will be created in the same directory - similar to Busybox
binaries. Note that this may not work in a =SLIME= repl since =sudo=
is called and might need input at the terminal.

#+begin_src lisp :dir ~/comp/core/ :package sk-user :eval never :exports code
  (sk-make *skel-project* :install-core)
#+end_src

You should see some output like the following:

#+begin_example
skel -> core -> /usr/local/bin/
homer -> core -> /usr/local/bin/
packy -> core -> /usr/local/bin/
rdb -> core -> /usr/local/bin/
organ -> core -> /usr/local/bin/
vc -> core -> /usr/local/bin/
gen -> core -> /usr/local/bin/
swm -> core -> /usr/local/bin/
#+end_example

**** Dependencies
:PROPERTIES:
:ID:       22b763b9-c781-4061-b5ef-fc4f19720cf0
:END:
If you do choose to build yourself without using =infra=, make sure
you're on GNU/Linux and have the required packages installed.

- *Required*
  - linux-headers
  - gcc
  - sbcl
  - emacs
  - quicklisp
  - rocksdb
  - zstd
  - mercurial
  - openssl

- /Optional/
  - cuda
  - evdev
  - jack
  - libjpeg-turbo
  - xkbcommon
  - ublksrv
  - keyutils
  - wasmer
  - sndfile
  - libssh2
  - btrfsutils
  - podman
  - qemu
  - gstreamer
  - rustls
  - tree-sitter
  - blake3
  - liburing
  - alsa
  - ffmpeg
  - glib
  - chromaprint
  - openblas (blas/lapack)
*** Configuration
:PROPERTIES:
:ID:       d9a1f958-c43e-4465-9916-3526f7a27268
:END:
The next thing you'll want to take care of is user configuration. You
can run any of the core apps without a configuration and it will
install a default one for you.

The only other /required/ development dependency which needs
configuring is Emacs.
**** Core
:PROPERTIES:
:ID:       db2ee1f1-846f-433c-9747-83ec18d47e40
:END:
The core is a single binary which dispatches on argv[0] from the
CLI. Each unique symlink to the core binary is treated as a separate
dispatch to a 'main' function like so:

#+begin_src lisp :exports code :eval never
  (define-multi-main dispatch-core
    (progn (in-package :core-lisp)
           ,#+nil ...)
    (:skel (bin/skel::start-skel))
    (:homer (bin/homer::start-homer))
    (:mpk (bin/mpk::start-mpk))
    ,#+nil ...)
#+end_src

The current apps that read a configuration file on startup are:
- skel - project management: =.skelrc=
- homer - home management: =.homerc=
- mpk - media production kit: =.mpkrc=

These apps all use the same /configuration object protocol/ from the
=OBJ/CONFIG= package and are printed to various S-Expression. Most
commonly the 'pretty' format is used which is simply a plist with
implied outer parentheses:

#+begin_src lisp :eval never
  :key1 val1
  :key2 val2
#+end_src

Canonically that would be:
#+begin_src lisp :eval never
  (:key1 val1
   :key2 val2)
#+end_src

**** Emacs
:PROPERTIES:
:ID:       6c87dbd0-0a4b-4395-bc70-fff94b680787
:END:
If you don't have your own Emacs config you can install the default CC
Emacs configuration using the =skel= command. 

- Warning :: this will overwrite files in your =~/.emacs.d= directory:
  #+begin_src shell :dir ~/comp/core/ :results output :exports both
  cd emacs && skel install
  #+end_src

  #+RESULTS:
  #+begin_example
  default.el -> /home/ellis/.emacs.d/default.el
  early-init.el -> /home/ellis/.emacs.d/early-init.el
  init.el -> /home/ellis/.emacs.d/init.el
  keys.el -> /home/ellis/.emacs.d/keys.el
  util.el -> /home/ellis/.emacs.d/util.el
  bar.el -> /home/ellis/.emacs.d/lib/bar.el
  c2.el -> /home/ellis/.emacs.d/lib/c2.el
  exec-path-from-shell.el -> /home/ellis/.emacs.d/lib/exec-path-from-shell.el
  graph.el -> /home/ellis/.emacs.d/lib/graph.el
  inbox.el -> /home/ellis/.emacs.d/lib/inbox.el
  mpk.el -> /home/ellis/.emacs.d/lib/mpk.el
  org-expiry.el -> /home/ellis/.emacs.d/lib/org-expiry.el
  publish-init.el -> /home/ellis/.emacs.d/lib/publish-init.el
  publish.el -> /home/ellis/.emacs.d/lib/publish.el
  scrum.el -> /home/ellis/.emacs.d/lib/scrum.el
  skel.el -> /home/ellis/.emacs.d/lib/skel.el
  skt.el -> /home/ellis/.emacs.d/lib/skt.el
  slime-cape.el -> /home/ellis/.emacs.d/lib/slime-cape.el
  slime-company.el -> /home/ellis/.emacs.d/lib/slime-company.el
  slime-repl-ansi-color.el -> /home/ellis/.emacs.d/lib/slime-repl-ansi-color.el
  sxp.el -> /home/ellis/.emacs.d/lib/sxp.el
  ulang.el -> /home/ellis/.emacs.d/lib/ulang.el
  uml-mode.el -> /home/ellis/.emacs.d/lib/uml-mode.el
  x86-lookup.el -> /home/ellis/.emacs.d/lib/x86-lookup.el
  #+end_example

The default config supports user customizations in a file with the
same name as the current user, so when the current =$USER= is ~ellis~
then we check for the file =ellis.el= and load it if it exists.

* Demo
:PROPERTIES:
:ID:       ec5dca14-eb23-4dac-962a-34f1a5d4fd1f
:CREATED:  <2025-07-07 Mon 14:11>
:END:
Core demo applications, examples, and tutorials can be found in the
[[gh:richardwesthaver/demo][demo repository]].
** Examples
:PROPERTIES:
:ID:       152b1e3d-d1ee-4098-bd98-38ebb0e14667
:CREATED:  <2025-07-07 Mon 14:10>
:END:

* Testing
:PROPERTIES:
:ID:       c074e53b-846d-45ed-8ddc-70e559ed6f0c
:END:
Each module in the core contains its own test suite located in the
=tests.lisp= file or =tests= directory and isolated to its own ASDF
system. The ASDF system is always the module name prefixed by
=/tests= - for example the =IO/TESTS= system is responsible for
testing the =IO= module system.

In addition to the test suite we have a set of experimental
benchmarks. These are kept in the top-level =bench= directory.

** Regression Tests
:PROPERTIES:
:ID:       74af2f86-9025-44c8-83de-d41816d623bf
:CREATED:  <2025-06-02 Mon 18:26>
:END:
Testing the core can be done from the CLI using =skel=:

#+begin_src sh :dir ~/comp/core/ :eval never
  # skel compile tests
  skel run tests
#+end_src

or from lisp:

#+begin_src lisp :eval never
  (ql:quickload :core/tests)
  (rt:run-all-tests)
#+end_src

** Benchmarks
:PROPERTIES:
:ID:       d2b45403-cec0-4b17-9295-d2ae7f19a1df
:CREATED:  <2025-06-02 Mon 18:26>
:END:

using =skel=:

#+begin_src sh :dir ~/comp/core/ :eval never
  # skel compile bench
  skel run bench db-stress
#+end_src

or from lisp:

#+begin_src lisp :eval never
  (ql:quickload :core/bench)
  (use-package :core/bench)
  (run-benchmark :db-stress)
#+end_src

#+RESULTS:
: #<PACKAGE "CORE/BENCH/DB/STRESS">

* Contributing
:PROPERTIES:
:ID:       e0657c76-395c-47b5-b5a6-1dcebd59ce7c
:CREATED:  <2025-06-02 Mon 19:36>
:END:
The core is currently a solo project and I don't plan on accepting
contributions in the near future. The core is its own private island,
isolated from the rest of the Common Lisp ecosystem and in almost all
cases contributions would be better directed towards other
packages.

See [[https://awesome-cl.com/][Awesome CL]] for a list of projects which could use additional
support, and take note the comments scattered throughout the core
source code which often reference popular packages from the ecosystem.
