#+title: Core User Manual
#+author: Richard Westhaver
#+email: ellis@rwest.io
#+property: header-args:shell :dir ~/comp/core/
#+setupfile: ../../clean.theme
#+texinfo_filename: core.info
#+texinfo_dir_category: Software development
#+texinfo_dir_title: Core: (core)
#+texinfo_dir_desc: CC Software Development Ecosystem

This manual documents the [[comp:][CC]] [[vc:core][core]] software suite. It is intended for
users/developers and assumes a intermediate level understanding of
computer programming concepts such as OOP, FP, IDEs, and the
shell. 

The core is a Lisp development system used to build next-gen
applications. It is composed of interconnected modules providing an
exceptionally powerful development ecosystem.

* Introduction
:PROPERTIES:
:ID:       156ffb70-9e00-4532-be47-b921c1825a91
:END:
Welcome to the *core*, the primary software development ecosystem of
[[comp:][CC]].

The core provides the foundation of all applications we produce. It is
optimized for rapid development of next-gen applications.

The core is highly opinionated - and these opinions are consistently
hard-coded into our development practices.

For example:
- *Linux is the only platform worth supporting*
  - We make no efforts to support cross-compilation or porting of our
    software to devices or operating systems the developer can't fully
    control such as Windows/MacOS/iOS/Android. We always assume the
    developer is running a GNU/Linux host.
- *Portability is over-rated*
  - CL implementations (lisps) share a base language but many
    parts of the ANSI CL spec are left up to interpretation: threads,
    OS, GC, MOP, etc
  - Many lisp packages attempt to account for as many lisps as
    possible via conditional compilation and wrappers - this clutters
    up the code base, is difficult to test, and is error-prone.
  - Instead of accounting for multiple compilers, we realize that we
    only need one - SBCL currently. The core does not contain any
    support for alternate lisps.
  - 'One true lisp' is all we need, and we're only concerned with
    /internal/ consistency - we are never bound by the choices in
    implementation made by other lisps (although there is much to
    learn from them).
- *Introspection is under-rated*
  - Black boxes (proprietary codes) are disrespectful to
    developers. Computer systems should be transparent by nature and
    make minimal efforts to 'hide' internal representations of data
    and code.
  - Never hide a part of the system, unless you have a very good
    reason for doing so.
- *Follow the Bleeding Edge*
  - We pull and rebuild the latest changes for all of our dependencies
    frequently
  - We host mirrors of all our major dependencies
  - Core development is always based on latest changes, can optionally
    downgrade for release builds where stability is valued
  - incorporate pre-release APIs and our own custom patches as needed.

* Overview
:PROPERTIES:
:ID:       ceb67759-c656-411d-a0c0-df19b18732e5
:END:
The core itself is not an application but is complex enough that it
merits its own dedicated manual. There is library-specific and API
[[id:2634e0bd-29b2-4191-9892-766abfa7435e][documentation]] available for the core, so what we are concerned with
here is the overall design, common patterns, and architecture of the
core environment.

This manual is often technical, but occassionally theoretical in
nature and intended for software developers with expertise in Lisp,
GNU/Linux, and Emacs.

The Core is a Lisp system. Common Lisp is our language of choice and
there is a decent amount of Emacs Lisp code too.

** Source Code
:PROPERTIES:
:ID:       66163a74-dc41-4679-bf83-a2c7598bb316
:CREATED:  <2025-06-02 Mon 20:54>
:END:
#+begin_src shell :eval no-export
ls -Ah
#+end_src

#+RESULTS:
| alien          |
| bootstrap.lisp |
| core.lisp      |
| core.sys       |
| etc            |
| .hg            |
| .hgignore      |
| .hgsub         |
| .hgsubstate    |
| ironclad       |
| lib            |
| ppcre          |
| readme.org     |
| skel           |
| skelfile       |
| slime          |
| .stash         |
| std            |

- Common Lisp \\
  The =STD= library lives under the [[vc:core/std][std]] directory, low-level FFI
  library bindings such as =ROCKSDB= under the [[vc:core/alien][alien]] directory and
  high-level user libraries like =RDB= under the [[vc:core/lib][lib]] directory. The
  [[vc:core/skel][skel]] directory contains the source of our multi-purpose project
  tool =SKEL=.
- Emacs Lisp \\
  The [[vc:core/etc/emacs][etc/emacs]] directory contains a complete Emacs configuration.

** Images
:PROPERTIES:
:ID:       346fbc32-b1d2-489b-9091-3767ba372281
:CREATED:  <2025-06-02 Mon 20:35>
:END:
*Images* refer to the binary file resulting from a call to
 =SAVE-LISP-AND-DIE=. According to SBCL this file contains:

#+begin_quote
enough information to restart a Lisp process later in the same state,
in the file of the specified name.
#+end_quote

See the function docs for details - there are many options available
which determine how the image can be used directly or dynamically from
other programs.

The =core images= we produce are executables which contain the full
SBCL runtime at their disposal. Note that these images can be quite
large - multiple gigabytes in some cases, and so care should be taken
when enabling additional build-time features.

Note that image-based development is quite unique. You start inside
your Lisp implementation's core image which contains the Lisp runtime
in its executable. The runtime in SBCL is compiled C code which you
may be included with the images you save to make them executable, or
you can remove it to save space. Restarting an image in the /exact
same state/ you saved it in is as simple as executing sbcl with the
=--core= argument or executing the saved core file (with runtime)
directly.

The development experience is exceptionally fluid when fully
appreciated. You have everything at your fingertips, always fully
compiled and ready to load into memory at a moment's notice.

Images are concatenative - they always build on an existing image. We
start with the ANSI LISP 'kernel' image, then we save it, extend it,
and repeat indefinitely. The natural evolution of this concept is to
have your *entire system in a Lisp image*. It is a 'maximalist'
philosophy which is deeply ingrained into the very idea of Lisp,
although ultimately relegated to the long-forgotten Lisp Machines.

Image-based development does come with its own set of foot guns - it
is more complex by nature and easy to end up in an unusable state when
you compile in faulty code. However the biggest conflict that arises
from images is that they are *anti-UNIX*.

GNU/Linux distributions today come with hundreds of binaries. The vast
majority of these are single-use tools with simple text interfaces
which aide themselves to composability via the shell. Lisp images are
not single-use tools - they always contain a complete Lisp runtime in
addition to any extensions you've added - so if you want to use them
like UNIX binaries with one image per application or tool, you're
duplicating a tremendous amount of code in each image[fn:1].

One of the goals of the =core= is to realize a full appreciation of
images and image-based development, starting from GNU/Linux Userspace
and working our way towards service management and then the
kernel. The general strategy is to reduce the OS environment while
extending our Lisp image. We aim to first serve as a default user
login shell, and ultimately challenge SystemD for PID1. If we are
successful, we will have a complete Lisp system compatible with the
Linux kernel.

[fn:1] Some Lisp applications developers do actually prefer this -
taking GNU/Linux and the UNIX philosophy as a constant in any
self-respecting OS.

* Getting Started
:PROPERTIES:
:ID:       636ffa98-c39a-4f2a-9a49-aa82497a8ca8
:END:
** Dependencies
:PROPERTIES:
:ID:       22b763b9-c781-4061-b5ef-fc4f19720cf0
:END:
To ensure dependencies on an existing system you should refer to the
[[comp:docs/infra/man][infra manual]].

A PKGBUILD recipe is planned but not ready AO [2026-04-18 Sat]. Note
that RocksDB should be installed via the =infra= project (the default
=extra/rocksdb= package is not compatible).

*** Required Dependencies
The following dependencies are _required_ - Arch Linux is assumed but
other distros should work.

- linux-headers
- gcc
- sbcl
- emacs
- rocksdb (built WITHOUT jemalloc)
  - gflags
  - intel-oneapi-tbb
- zstd
- mercurial
- openssl

*** Optional Dependencies
Some of these dependencies may already be installed on your system,
others will need to be installed manually or via [[vc:infra][infra]].

- cuda
- evdev
- jack
- libjpeg-turbo
- xkbcommon
- keyutils
- sndfile
- libssh2
- btrfsutils
- gstreamer
- tree-sitter
- blake3
- liburing
- alsa
- ffmpeg
- chromaprint
- openblas (blas/lapack)

** Bootstrap
:PROPERTIES:
:ID:       dcb3ffff-5388-4387-8a46-553ae0309d70
:END:
Bootstrapping from SBCL is quite easy. Once all required dependencies
are installed, just run [[vc:core/bootstrap.lisp][bootstrap.lisp]]:
#+begin_src shell :eval never :exports code
# clone the source code from a mirror
git clone https://codeberg.org/c-c/core
cd core
sbcl --script bootstrap.lisp
sudo .stash/core --script etc/script/install.lisp
#+end_src

Release tarballs are planned but not available AO [2026-04-18 Sat].

** Configuration
:PROPERTIES:
:ID:       d9a1f958-c43e-4465-9916-3526f7a27268
:END:
The next thing you'll want to take care of is user configuration. You
can save your configuration at your preferred XDG-compliant location
(=~/.config/corerc= is recommended).

#+begin_src lisp :var path-to-core="~/comp/core/" path-to-shed="~/comp/shed/" :package user :results output replace
;;; .corerc --- core init file -*- mode: common-lisp; -*-
(init :xdg) ;; apply user XDG config
(init :term) ;; detect current terminal
(init :log :level :debug) ;; enable global logger
;; index local systems
(init :sys :sysdefs (append (sysdefs path-to-core t) #+optional (sysdefs path-to-shed t)))
#+end_src

#+RESULTS:

The only other development dependency which needs configuring is
Emacs. This can be done via the =skel= tool, but keep in mind that
this will overwrite the XDG-compliant emacs configuration directory
(=~/.config/emacs=) if it exists:

#+begin_src shell :results output replace
skel make install-emacs
#+end_src

#+RESULTS:
: #:debug 0.140999
: ; (#<rule install-emacs>)

*** Core
:PROPERTIES:
:ID:       db2ee1f1-846f-433c-9747-83ec18d47e40
:END:
The core is a single binary which dispatches on argv[0] from the
CLI. Each unique symlink to the core binary is treated as a separate
dispatch to a 'main' function like so:

#+begin_src lisp :exports code :eval never
  (define-multi-main dispatch-core
    (progn (in-package :core-lisp)
           ,#+nil ...)
    (:skel (bin/skel::start-skel))
    (:homer (bin/homer::start-homer))
    (:mpk (bin/mpk::start-mpk))
    ,#+nil ...)
#+end_src

The default path (when argv[0]=core) accepts a lisp file as
configuration just like =~/.sbclrc=, =corerc= respected the
=XDG_CONFIG_HOME= variable though and may be located in
=~/.config/corerc=.

The current apps that read a configuration file on startup are:
- skel - project management: =skelrc=
- homer - home management: =homerc=
- mpk - media production kit: =mpkrc=

By default they are located under =XDG_CONFIG_HOME=.

These apps all use the same /configuration object protocol/ from the
=OBJ/CONFIG= package and are printed to various S-Expression. Most
commonly the 'pretty' format is used which is simply a plist with
implied outer parentheses:

#+begin_src lisp :eval never
  :key1 val1
  :key2 val2
#+end_src

Canonically that would be:
#+begin_src lisp :eval never
  (:key1 val1
   :key2 val2)
#+end_src

*** Emacs
:PROPERTIES:
:ID:       6c87dbd0-0a4b-4395-bc70-fff94b680787
:END:
If you don't have your own Emacs config you can install the default CC
Emacs configuration using the =skel= command. 

- Warning :: this will overwrite files in your =.emacs= directory (defaults to =$XDG_CONFIG_HOME/emacs/=:
  #+begin_src shell :dir ~/comp/core/ :results output :exports both
  skel make install-emacs
  #+end_src

  #+RESULTS:
  : #:debug 0.139999
  : ; (#<rule install-emacs>)

The default config supports user customizations in a file with the
same name as the current user, so when the current =$USER= is ~ellis~
then we check for the file =ellis.el= and load it if it exists.

** Demos
:PROPERTIES:
:ID:       ec5dca14-eb23-4dac-962a-34f1a5d4fd1f
:CREATED:  <2025-07-07 Mon 14:11>
:END:
Core demo applications, examples, and tutorials can be found in the
[[vc:demo][demo]] project with documentation [[comp:docs/demo][available online]].
** Testing
:PROPERTIES:
:ID:       c074e53b-846d-45ed-8ddc-70e559ed6f0c
:END:
Each module in the core contains its own test suite located in the
=tests.lisp= file or =tests= directory and isolated to its own
system. The system is always the module name with a suffix of
=/tests= - for example the =IO/TESTS= system is responsible for
testing the =IO= module system.

*** Regression Tests
:PROPERTIES:
:ID:       74af2f86-9025-44c8-83de-d41816d623bf
:CREATED:  <2025-06-02 Mon 18:26>
:END:
Testing the core can be done from the CLI using =skel=:

#+begin_src shell :eval no
  # skel compile tests
  skel run tests
#+end_src

or from lisp:

#+begin_src lisp :eval no
  (test-system :core)
#+end_src

** Documentation
:PROPERTIES:
:ID:       2634e0bd-29b2-4191-9892-766abfa7435e
:CREATED:  <2025-09-30 Tue 21:48>
:END:
Module-level documentation is available in the [[comp:docs/core/lib][lib]] directory. This
documentation is partially auto-generated, but generally reserved for
extended developer documentation. Not all systems are guaranteed to be
covered.

AO [2026-04-18 Sat] full-auto API docs are planned but not
available. They will be located under the [[comp:core/docs/api][api]] directory.

** Contributing
:PROPERTIES:
:ID:       e0657c76-395c-47b5-b5a6-1dcebd59ce7c
:CREATED:  <2025-06-02 Mon 19:36>
:END:
The core is a solo experiment and I don't plan on accepting
contributions in the near future. The core is its own private island,
isolated from the rest of the Common Lisp ecosystem and in almost all
cases contributions would be better directed towards other packages.

See [[https://awesome-cl.com/][Awesome CL]] for a list of projects which could use additional
support, and take note the comments scattered throughout the core
source code which often reference popular packages from the ecosystem.
* Concepts
:PROPERTIES:
:ID:       8e379ae7-5eca-4ccb-8603-e32a20ef2d37
:CREATED:  <2025-09-30 Tue 21:49>
:END:
** Systems
:PROPERTIES:
:ID:       d0f002d4-f42e-4aad-b8fe-9a2a930a696f
:CREATED:  <2026-04-18 Sat 22:18>
:END:
** Logical Hosts
:PROPERTIES:
:ID:       eb6edfd5-632f-43d4-aa93-fc07a523e8b1
:CREATED:  <2026-04-17 Fri 19:09>
:END:
[[id:bbdc87f1-cece-474f-905e-d02401e82510][Logical Pathnames]] are used sparingly in the ~core~ source but their
use is encouraged by users. Several logical hosts are pre-defined in
addition to the SBCL =SYS= host.

#+begin_src lisp
(list-all-logical-host-names)
#+end_src

#+RESULTS:
| ETC | MEDIA | SCRATCH | SRV | STASH | STORE | SYS | USER | USR | VAR |

*** VAR
:PROPERTIES:
:ID:       d4aba737-7ed5-4548-919e-4f54b48a65f1
:CREATED:  <2026-05-04 Mon 21:01>
:END:
*** SRV
:PROPERTIES:
:ID:       c5f3eeef-3a7e-43f7-a87d-41eb53656ad0
:CREATED:  <2026-05-04 Mon 21:01>
:END:
*** ETC
:PROPERTIES:
:ID:       c95d90be-377f-4145-8626-56bc6a82a8f6
:CREATED:  <2026-05-04 Mon 21:31>
:END:
*** USR
:PROPERTIES:
:ID:       da86a850-3b31-434f-b7fb-eb1868ce7ce1
:CREATED:  <2026-05-04 Mon 21:01>
:END:
*** USER
:PROPERTIES:
:ID:       50ddd65b-0114-40a3-9965-c03a1822e7cc
:CREATED:  <2026-05-04 Mon 21:05>
:END:
*** STASH
:PROPERTIES:
:ID:       1d9a49b3-c7c6-427c-9cd0-ae9f174d243f
:CREATED:  <2026-04-18 Sat 22:59>
:END:
*** STORE
:PROPERTIES:
:ID:       9b0ab705-85ac-45d2-898d-97ce83faa98f
:CREATED:  <2026-05-04 Mon 21:00>
:END:
** Reader
:PROPERTIES:
:ID:       2f1fd6e4-af27-4128-99dc-078216d1105c
:CREATED:  <2026-04-18 Sat 23:01>
:END:
** Printer
:PROPERTIES:
:ID:       9943ef84-5484-4d3a-b33b-1ac96a9cd59c
:CREATED:  <2026-04-18 Sat 23:01>
:END:
** Macros
:PROPERTIES:
:ID:       22cb1cff-c5d3-4c98-9a31-cbd5c0403a98
:CREATED:  <2026-04-18 Sat 22:16>
:END:
*** DSLs
:PROPERTIES:
:ID:       66a1a653-29b1-4446-a66e-a3587979edca
:CREATED:  <2026-04-17 Fri 19:10>
:END:
*** Memoization
:PROPERTIES:
:ID:       3dc4b9cd-56fa-46b9-b747-7a71704e755b
:CREATED:  <2026-04-18 Sat 22:17>
:END:
* Protocols
:PROPERTIES:
:ID:       bc25aea1-1375-405e-b091-6660e21e9916
:CREATED:  <2025-09-30 Tue 21:56>
:END:
~Protocols~ are keyed groupings of symbols, sort of like light-weight
packages.

#+begin_src lisp :results replace
(fmt-tree nil (find-module :std :proto :kernel) :plist t :layout :down)
#+end_src

#+RESULTS:
#+begin_example
:KERNEL
 ├─ :PACKAGE
 │   ╰─ :STD/PRIM
 ├─ :DESCRIPTION
 │   ╰─ "Standard funcallable object extensions."
 ├─ :VARIABLES
 │   ╰─ (*KERNEL*)
 ├─ :CONDITIONS
 │   ╰─ (KERNEL-INIT-ERROR NO-KERNEL-ERROR)
 ├─ :ACCESSORS
 │   ╰─ (KERNEL KERNEL-INFO KERNEL-DOCUMENTATION)
 ├─ :METHODS
 │   ╰─ (KERNEL-EXPRESSION)
 ├─ :FUNCTIONS
 │   ╰─ (CHECK-KERNEL MAKE-KERNEL)
 ├─ :MACROS
 │   ╰─ (DEFKERNEL)
 ├─ :PREDICATES
 │   ╰─ (KERNELP)
 ╰─ :CLASSES
     ╰─ (KERNEL-CLASS KERNEL-OBJECT)
#+end_example

Protocols are designated by a key with an associated plist (the cdr of
~(find-module ... :proto ...)~). The list of available /plist/ keys in
a protocol are identified by a variable:

#+begin_src lisp :results list
std/defsys::*protocol-keyword-imports*
#+end_src

#+RESULTS:
- :METHODS
- :FUNCTIONS
- :TYPES
- :VARIABLES
- :CONSTANTS
- :PARAMETERS
- :MACROS
- :CONDITIONS
- :RESTARTS
- :ACCESSORS
- :PREDICATES
- :CLASSES
- :STRUCTS
- :DECLARATIONS
- :GLOBALS

* Skel
:PROPERTIES:
:ID:       01613601-0dc2-4d4d-9354-7ffcc0a1eaed
:CREATED:  <2025-09-30 Tue 21:58>
:END:
#+begin_src shell :results pp replace :exports both
skel help
#+end_src

#+RESULTS:
: skel v0.1.1:10e375b07907 --- A universal project development tool.
: usage: skel [opts] <command> [<arg>]

The =skel= tool is an extensible program designed around the idea of
[[id:359441da-1b61-4d73-8563-605ea7262b58][projects]].

** Architecture
:PROPERTIES:
:ID:       4fd2d7eb-e738-4e2f-8de1-3b8f5671d488
:END:
*** Core
:PROPERTIES:
:ID:       35a5aa3b-1ff1-46ea-9ec7-1d6c9a2386f2
:CREATED:  <2026-01-03 Sat 20:09>
:END:
The library core is built on CLOS. Most important data structures are
represented with classes, slots, and methods such as the =SK-PROJECT=
class which is based on the =OBJ:PROJECT= class (a generic project
type).

#+begin_src lisp :results list
(mapcar 'name (components (find-component :core (find-system :skel))))
#+end_src

#+RESULTS:
- condition
- proto
- header
- var
- obj
- component
- rule
- project
- pack
- print
- schema
- db
- log
- util

*** Components
:PROPERTIES:
:ID:       c86d03b4-dc7d-4836-8bdb-58498bd84e46
:CREATED:  <2026-01-03 Sat 20:09>
:END:
In addition to the core objects we provide a set of =SK-COMPONENT=
definitions which convert core objects to a corresponding external
representation. For example the =makefile= class defined in
=comp/makefile.lisp= can be built from or consumed by a project.

#+begin_src lisp :results list
(mapcar 'name (components (find-component :comp (find-system :skel))))
#+end_src

#+RESULTS:
- lisp
- asd
- cargo
- box
- container
- org
- dir-locals
- makefile
- sys
- infer

*** Apps
:PROPERTIES:
:ID:       6e3a9575-a6d9-46e7-a0cf-7f4bbde91040
:CREATED:  <2026-05-04 Mon 21:36>
:END:
The ~skel~ system is further extended by built-in ~applications~ which
specialize on skel objects in project domains of particular interest.

There are currently 4 apps in addition to skel itself:

- homer :: Home Management
- packy :: Package Management
- krypt :: Secrets Management
- mpk :: Media Management

** Configuration
:PROPERTIES:
:ID:       2658a3d1-cfa5-436e-b2b0-9cf42a6f66c6
:END:
The ~skel~ tool can be configured at runtime using the CLI flags, or
via local configuration files. The configuration files are in the
~skelfile~ format and are assigned the following locations by default:
- =*user-skelrc*= :: =$XDG_CONFIG_HOME/skelrc=
- =*system-skelrc*= :: =/etc/skelrc=

Both files are optional and the user skelrc takes precedence over
system.

Example =~/.config/skelrc=:
#+begin_src shell :results output :exports both
cat ~/.config/skelrc
#+end_src

#+RESULTS:
#+begin_example
;;; skelrc @ 2023-10-12.02:58:08 -*- mode: skel; -*-
:name "Richard Westhaver"
:email "richard.westhaver@gmail.com"
:version "0.1.0"
:fmt :pretty
:vc :hg
:auto-insert t
:license :mpl2
:logger (:level :info)
:stash ".stash"
:store "/opt/store"
:scripts ("~/.stash/scripts")
#+end_example

** Projects
:PROPERTIES:
:ID:       359441da-1b61-4d73-8563-605ea7262b58
:END:
Projects are the highest-level objects int the ~skel~ system. A
project consists of a list of slots which are populated automatically
or by the user. Once a project is initialized the slots can be
accessed and a set of high-level operations can be performed.

The easiest way to initialize a project is with a ~skelfile~. These
files are parsed as a simplified Lisp dialect and generate
~sk-project~ objects based on their contents.

The simplest project looks like this:

#+begin_src lisp :eval never :name skelfile-hello
:name hello-world
#+end_src

Don't worry, this is still lisp - the parentheses are implied. All we
actually need is a name to generate an object, and we can fill in the
blanks later as the project develops.

Here is a more verbose example, still with only metadata:

#+begin_src lisp :eval never
;;; skelfile --- core skelfile -*- mode: skel; -*-
:name "core"
:author "Richard Westhaver <ellis@rwest.io>"
:version "0.1.0"
:license "MPL"
:description "The Compiler Company Core"
:vc :hg
:tags ("core")
:docs ((:org "readme") (:org "install") (:org "tests") (:org "todo"))
:include ("emacs/emacs.sk")
#+end_src

Another example with rules and components:

#+begin_src lisp :eval never :name skelfile-simple
;;; skelfile @ 2023-10-08.02:37:25 -*- mode: skel; -*-
:name skel
:author "ellis"
:version "0.1.0"
:description "a hacker's project compiler"
:license "MPL"
:vc :hg
:tags ("lisp")
:rules ((build () (print (asdf:make :skel/cli)))
        (clean () #$rm -rf */*.fasl$#))
:docs ((:org "readme"))
:components
((:elisp "sk"))
:stash "~/.stash"
#+end_src

The currently accessible ~sk-project~ be easily inferred via the
~init~ protocol:
#+begin_src lisp :results output replace
(init :skel) ;; find the top-level skel project
(describe *skel-project*)
#+end_src

#+RESULTS:
#+begin_example
#<project ORG :components 0 :rules 16>
  [standard-object]

Slots with :INSTANCE allocation:
  NAME                           = ORG
  PATH                           = #P"/home/ellis/comp/org/skelfile"
  AUTHOR                         = ("Richard Westhaver" . "ellis@rwest.io")
  VERSION                        = "0.1.0"
  TAGS                           = (ORG DOCS NOTES META PLAN ARCHIVE GRAPH)
  DESCRIPTION                    = "CC Org Files"
  LICENSE                        = "MPL"
  AST                            = NIL
  ID                             = 1784914079056115652
  VC                             = #<VC/HG:HG-REPO {12092CE183}>
  SRC                            = #P"/home/ellis/comp/org/"
  STASH                          = #P"/home/ellis/comp/org/.stash/"
  STORE                          = #P"/home/ellis/comp/org/.stash/store/"
  CACHE                          = #P"/home/ellis/comp/org/.stash/cache/"
  COMPONENTS                     = #()
  BIND                           = ((SUBMODS (LIST "graph" "meta" "plan" "docs" "notes" "archive")))
  PHASES                         = #<HASH-TABLE :TEST EQL :COUNT 3 {1209251613}>
  RULES                          = #(#<rule default (build publish deploy dist-html dist-source..
  INCLUDE                        = #()
#+end_example

*** Components
:PROPERTIES:
:ID:       bc8d6372-01aa-49e1-a019-d22b03dd7e80
:CREATED:  <2026-05-16 Sat 22:29>
:END:
*** Rules
:PROPERTIES:
:ID:       0d22af45-3e2a-43f9-af61-2df1e2629cb8
:CREATED:  <2026-05-16 Sat 22:29>
:END:
Skel ~rules~ are the Lisp equivalent of Makefile rules. They are
almost always executed at the CLI via the =make= command.

Rules are a project slot so you can list them with =show=:
#+begin_src shell :results output replace
skel show rules
#+end_src

#+RESULTS:
#+begin_example
#<rule default (data rebuild-core)>
#<rule bootstrap (data build-core)>
#<rule data (%stash psl.dat kbd.sxp x11.lisp parquet.json)>
#<rule all (%stash psl.dat x11.lisp kbd.sxp parquet.thrift rebuild-core deploy)>
#<rule upstream>
#<rule clean>
#<rule update-readme>
#<rule psl.dat (%stash)>
#<rule kbd.sxp (%stash)>
#<rule ccadb.dat (%stash)>
#<rule rgb.txt (%stash)>
#<rule x11.lisp (rgb.txt)>
#<rule parquet.thrift (%stash)>
#<rule parquet.json (%stash)>
#<rule freedesktop.org.xml (%stash)>
#<rule parquet-test-data (%stash)>
#<rule sndfile-test-data (%stash)>
#<rule ffmpeg-test-data (%stash)>
#<rule test-data (ffmpeg-test-data sndfile-test-data parquet-test-data)>
#<rule %stash>
#<rule ssl-certs>
#<rule ssl-client-certs>
#<rule install-emacs>
#<rule purge-emacs>
#<rule build-core (%stash)>
#<rule rebuild-core (%stash)>
#<rule compile-core>
#<rule install-core>
#<rule install-emacs>
#<rule run-tests>
#<rule save-tests>
#<rule compile-tests>
#<rule compile-core>
#<rule coverage>
#<rule install (install-core)>
#<rule syms.sxp>
#<rule dist>
#<rule dist-repo>
#<rule dist-source>
#<rule build-docs>
#<rule build-core (%stash)>
#<rule deploy (dist dist-repo)>
#+end_example

Unlike makefile rules we don't need to specify a ~target~ (although
one may be provided for build caching).

Each rule is associated with a function, or more precisely a ~closure~
with bindings determined by the ~bind~ slot of a project:

#+begin_src shell
skel show bind
#+end_src

#+RESULTS:
: (STASH .stash)

The ~RULE~ class is defined in the ~PROJECT~ protocol:

#+begin_src lisp
(let ((class (find-class 'project:rule)))
  (values 
   (make-instance class)
   (mapcar 'name (class-slots class))))
#+end_src

#+RESULTS:
: #<RULE (LAMBDA (&REST ARGS) IN ALLOCATE-STANDARD-FUNCALLABLE-INSTANCE)>
: (ID AST)
**** Simple Rules
:PROPERTIES:
:ID:       7160a8be-497e-433c-b27a-6ae1a1c1b443
:CREATED:  <2026-05-17 Sun 14:50>
:END:
#+begin_src lisp
(let ((class (find-class 'project:simple-rule)))
  (values 
   (make-instance class)
   (mapcar 'name (class-slots class))))
#+end_src

#+RESULTS:
: #<SIMPLE-RULE (LAMBDA (&REST ARGS) IN ALLOCATE-STANDARD-FUNCALLABLE-INSTANCE)>
: (ID AST SOURCE OBJ/PROJECT::TARGET)

**** Interactive Rules
:PROPERTIES:
:ID:       e34102c2-332e-4d7d-a3ec-5bc57f1d7777
:CREATED:  <2026-05-16 Sat 22:37>
:END:
#+begin_src lisp
(let ((class (find-class 'project:interactive-rule)))
  (values 
   (make-instance class)
   (mapcar 'name (class-slots class))))
#+end_src

#+RESULTS:
: #<INTERACTIVE-RULE (LAMBDA (&REST ARGS)
:                      IN
:                      ALLOCATE-STANDARD-FUNCALLABLE-INSTANCE)>
: (ID AST INTERACTIVE OBJ/PROJECT::ARGS)

Interactive rules implement the ~COMMAND~ protocol and accept a
lambda-list and ~INTERACTIVE~ declaration in the body. They are
commonly used as project-specific subcommands.

* Hacking
:PROPERTIES:
:ID:       a2797272-550f-4b96-a0c5-c0660af57d05
:CREATED:  <2025-09-30 Tue 21:56>
:END:
Lisp is by nature a hacking-friendly language, and every effort is
made to preserve those properties throughout the core. As a result it
is easy to change any symbol and modify any place in a running core
system, although the consequences may range from unexpected to
catastrophic if attempts are made to use or modify
internals. Especially when dealing with ~alien~ objects it's just as
easy to corrupt your Lisp image as it is to modify it.

When hacking on the source refer to the [[comp:docs/core/lib][library]] docs and take note of
the file comments, particularly inline tasks.
