#+title: Core User Manual
#+author: Richard Westhaver
#+email: ellis@rwest.io
#+property: header-args :dir ~/comp/core/ :eval no-export
#+setupfile: ../../clean.theme
#+texinfo_filename: core.info
#+texinfo_dir_category: Software development
#+texinfo_dir_title: Core: (core)
#+texinfo_dir_desc: CC Software Development Ecosystem

This manual documents the [[comp:][CC]] [[vc:core][core]] software. The core is a
multi-language library and framework used to build novel
applications. It is composed of language-specific collections of
interconnected libraries providing an exceptionally powerful
development ecosystem.

* Introduction
:PROPERTIES:
:ID:       156ffb70-9e00-4532-be47-b921c1825a91
:END:
Welcome to the *core*, the primary software development ecosystem of
[[comp:][CC]].

Here you will find a large collection of interconnected modules and
tools which forms the foundation of all applications we produce. The
core is designed to be the best toolkit for rapid development of
next-gen applications.

To achieve this end we narrow the scope of our work in many ways and
have some hard-coded opinions worth mentioning.

For example, we make no efforts to support cross-compilation or
porting of our software to devices or operating systems the developer
can't fully control such as Windows/MacOS/iOS/Android. We always
assume the developer is running a GNU/Linux host.

We also don't obey any rules regarding backward-compatibility. APIs
change fast and breaking changes may be introduced without notice.

We track the development branches and host mirrors of all of our major
dependencies including SBCL and Emacs as well as
libraries including RocksDB and Zstd so that we can incorporate
pre-release APIs and our own custom patches as needed. Internally we
do not test against public release binaries and only support binaries
built from our own mirrors.

** COMMENT bleh
:PROPERTIES:
:ID:       0cb05ffe-b06c-4f89-b2a2-b5f87faf04bd
:END:
The idea of a =core= is one that is quite common in software
design. It implies something that is fundamental - the machine behind
the machine, whatever the machine may be.

The =core= is often the most important part of your application - the
one you want to get right. Where things get tricky is when you have
many different applications, all which have a =core=, which you also
need to get right.

The natural evolution is to start abstracting away the commonalities
between your application core, refactoring them into a new project. As
your applications grow, new patterns appear. You keep searching for
common patterns and refactoring. This pattern repeats and all is good
and dandy.

That is, until your applications start to die. No matter the manner or
pace of death, there is a symbiotic link with the =core= that is
broken when your application is no longer useful, or there is another
application that takes its place. As a result, the parts of your
=core= that were heavily influenced by the deceased application start
to become less useful too. If left unchecked, your core will turn into
bloat.

This is *not* how the CC core is developed. Our core does not inherit
from applications and is not dependent on them. We are not building a
'top-down' system. Instead, we build 'bottom-up' from scratch and keep
our core insulated (but not completely isolated) from applications.

* Overview
:PROPERTIES:
:ID:       ceb67759-c656-411d-a0c0-df19b18732e5
:END:
The Core itself is not an application but is complex enough that it
merits its own dedicated manual. There are dedicated manuals for the
applications which are part of the core, so what we are concerned with
here is managing and hacking on the source code itself. We are
directing our attention inwards, towards the core instead of extending
our gaze away from it to see where it leads.

This manual is often technical, but occassionally theoretical in
nature and intended for software developers with experience in Linux,
Lisp, and Emacs.

The Core is primarily a Lisp code base. Common Lisp is our language of
choice and there is a significant amount of Emacs Lisp code too. Other
languages which are present include C as well as Rust.

A solid understanding of C is recommended for developing on the Core,
but is not a hard requirement. We make heavy use of FFI to communicate
with the OS as well as C libraries but we provide high-level Lispy
bindings in most cases.

The Rust portions of the code base are currently under construction
and isolated from the rest of the Core. In the future we may
incorporate it into this manual, but for the purpose of the following
we may safely ignore it.

* Getting Started
:PROPERTIES:
:ID:       636ffa98-c39a-4f2a-9a49-aa82497a8ca8
:END:
*** Dependencies
:PROPERTIES:
:ID:       22b763b9-c781-4061-b5ef-fc4f19720cf0
:END:
**** Minimum Requirements
:PROPERTIES:
:ID:       2b2485b6-29d1-4ead-aaf5-91e4798c5779
:END:
- GNU/Linux, linux-headers
- C compiler (GCC, MUSL, CLANG)
- SBCL
- GNU Emacs
- Quicklisp
- RocksDB
- Zstd
- Mercurial
- OpenSSL
- Treesitter
- BLAKE3
**** Optional Requirements
:PROPERTIES:
:ID:       3089b83f-1bd1-423e-9e09-48c839fbac07
:END:
- Rust
- X11
- CUDA
- Libevdev
- Libkeyutils
- Wasmer
- Libsndfile
- Libreadline
- Libssh2
- Btrfs
- Podman
- QEMU
- CUDA
- Readline
- GStreamer
- Rustls
*** Bootstrap
:PROPERTIES:
:ID:       dcb3ffff-5388-4387-8a46-553ae0309d70
:END:
Bootstrapping the core can be done via an existing core image or the
=skel= binary in a 'self-bootstrapping' fashion. See the [[comp:docs/infra][infra]] project
documentation for details on that process.

Bootstrapping from source is quite easy too. All that is needed is to
get the source, load the project =skelfile= and run =sk-make=.

  #+begin_src shell :eval never :exports code
    # clone the source code from a mirror
    git clone https://codeberg.org/c-c/core
    cd core
    sbcl
  #+end_src

Then in the SBCL REPL:
#+begin_src lisp :dir ~/comp/core/ :exports both
  (ql:quickload :skel)
  (in-package :sk-user)
  (init-skel)
  (sk-make *skel-project* :all)
#+end_src

#+RESULTS:
| :ALL |

Installation is trivial and can be done from the same REPL session. By
default the =core= binary will be written to =/usr/local/bin/= and a
series of symlinks will be created in the same directory - similar to
Busybox binaries. Note that this may not work in a =SLIME= repl since
=sudo= is called and might need input at the terminal.

#+begin_src lisp :dir ~/comp/core/ :package sk-user :eval never :exports code
  (sk-make *skel-project* :install-core)
#+end_src

You should see some output like the following:

#+begin_src 
skel -> core -> /usr/local/bin/
homer -> core -> /usr/local/bin/
packy -> core -> /usr/local/bin/
rdb -> core -> /usr/local/bin/
organ -> core -> /usr/local/bin/
vc -> core -> /usr/local/bin/
gen -> core -> /usr/local/bin/
swm -> core -> /usr/local/bin/
#+end_src

*** Configuration
:PROPERTIES:
:ID:       d9a1f958-c43e-4465-9916-3526f7a27268
:END:
The next think you'll want to take care of is user configuration.
**** Emacs
:PROPERTIES:
:ID:       6c87dbd0-0a4b-4395-bc70-fff94b680787
:END:
If you don't have your own Emacs config you can install the default CC
Emacs configuration using the =skel= command. 

- Warning :: that this will mess with your =~/.emacs.d= directory:
  #+begin_src shell :dir ~/comp/core/ :results output :exports both
  cd emacs && skel install
  #+end_src

  #+RESULTS:
  #+begin_example
  default.el -> /home/ellis/.emacs.d/default.el
  early-init.el -> /home/ellis/.emacs.d/early-init.el
  init.el -> /home/ellis/.emacs.d/init.el
  keys.el -> /home/ellis/.emacs.d/keys.el
  util.el -> /home/ellis/.emacs.d/util.el
  c2.el -> /home/ellis/.emacs.d/lib/c2.el
  exec-path-from-shell.el -> /home/ellis/.emacs.d/lib/exec-path-from-shell.el
  graph.el -> /home/ellis/.emacs.d/lib/graph.el
  inbox.el -> /home/ellis/.emacs.d/lib/inbox.el
  mpk.el -> /home/ellis/.emacs.d/lib/mpk.el
  org-expiry.el -> /home/ellis/.emacs.d/lib/org-expiry.el
  publish.el -> /home/ellis/.emacs.d/lib/publish.el
  scrum.el -> /home/ellis/.emacs.d/lib/scrum.el
  sk.el -> /home/ellis/.emacs.d/lib/sk.el
  skt.el -> /home/ellis/.emacs.d/lib/skt.el
  slime-cape.el -> /home/ellis/.emacs.d/lib/slime-cape.el
  slime-company.el -> /home/ellis/.emacs.d/lib/slime-company.el
  slime-repl-ansi-color.el -> /home/ellis/.emacs.d/lib/slime-repl-ansi-color.el
  sxp.el -> /home/ellis/.emacs.d/lib/sxp.el
  ulang.el -> /home/ellis/.emacs.d/lib/ulang.el
  uml-mode.el -> /home/ellis/.emacs.d/lib/uml-mode.el
  #+end_example

The default config supports user customizations in a file with the
same name as the current user, so when =$USER = ellis= then we check
for =ellis.el= and load it if it exists in =~/.emacs.d/=.

**** SBCL
:PROPERTIES:
:ID:       52a44b82-d5e8-4926-83e9-2944b1df8e62
:END:

**** Core Apps
:PROPERTIES:
:ID:       db2ee1f1-846f-433c-9747-83ec18d47e40
:END:
The core is a single binary which dispatches on argv[0] from the
CLI. Each unique symlink to the core binary is treated as a separate
dispatch to a 'main' function like so:
#+begin_src lisp :exports code
  (define-multi-main dispatch-core
    (progn (in-package :core-lisp)
           ,#+nil ...)
    (:skel (bin/skel::start-skel))
    (:homer (bin/homer::start-homer))
    (:mpk (bin/mpk::start-mpk))
    ,#+nil ...)
#+end_src

The current apps that read a configuration file on startup are:
- skel - project management: =.skelrc=
- homer - home management: =.homerc=
- mpk - media production kit: =.mpkrc=

These apps all use the same /configuration object protocol/ from the
=OBJ/CONFIG= package and are serialized to various S-Expression
interpretations. Most commonly the 'pretty' format is used which
is simply a plist with implied outer parentheses:
#+begin_src lisp :eval never
  :key1 val1
  :key2 val2
#+end_src

Canonically that would be:
#+begin_src lisp :eval never
  (:key1 val1
   :key2 val2)
#+end_src
***** Skel
:PROPERTIES:
:ID:       d666962c-e15e-430c-8997-bf5a80bb9632
:END:
A skel config in 'canonical' format (plain S-Expression) is written to
=~/.skelrc= the first time you run it from the CLI, if it does not
already exist.

***** Homer
:PROPERTIES:
:ID:       526513cb-5b7a-4cc0-8d91-739db3e635f6
:END:

***** Mpk
:PROPERTIES:
:ID:       1acfa6a4-41df-4ab7-84dd-72656cff0889
:END:

* Testing
:PROPERTIES:
:ID:       c074e53b-846d-45ed-8ddc-70e559ed6f0c
:END:

