#+title: MPK
#+description: Media Production Kit
#+setupfile: ../../../clean.theme
=mpk= is our Media Production Kit. It is optimized for processing and
maintaining mid-sized collections of mixed media (10-100TB).

- codecs
  - MIDI
  - OSC
- interfaces
  - mpd
  - ytdl
  - GStreamer
  - sndfile
  - chromaprint
  - transmission
  - ffmpeg
  - picard
- features
  - mlm (library manager)
  - metro (MIDI/OSC client/server)
  - STASH/SESH client/servers
  - players (audio/video, streaming, DRM)

#+BEGIN: lisp-system-info :system mpk :tests nil
- packages
  #+CALL: lisp-system-packages[:post transpose]("mpk")

  #+RESULTS:

- dependencies
  #+CALL: lisp-system-dependencies[:post transpose]("mpk")

  #+RESULTS:

- dependents
  #+CALL: lisp-system-dependents[:post transpose]("mpk")

  #+RESULTS:

- files
  #+CALL: lisp-system-files[:post transpose]("mpk")

  #+RESULTS:

- symbols
  #+CALL: lisp-package-symbols[:post transpose]("MPK")

  #+RESULTS:

#+END:

* Protocol
:PROPERTIES:
:ID:       4c8790ef-ca92-472b-b0ff-5f00c1752f62
:CREATED:  <2025-07-08 Tue 17:40>
:END:
The protocol provided by the =mpk= package can be thought of as a
cross between =skel= and =dsp=. =mpk-project= and =mpk-component=
inherit directly from =sk-project= and =sk-component=. Many of the
generic methods provided operate on =media-file= objects and use =dsp=
internals.

* Configuration
:PROPERTIES:
:ID:       6168e56a-694b-4eb8-9a36-d2167390ce48
:CREATED:  <2025-07-08 Tue 16:56>
:END:
=mpk= supports configuration in the standard s-expression
format. Where possible we also support the default file formats used
by the tools we rely on (picard, transmission, mpd).

#+begin_src lisp :results output :package mpk
  (describe 'mpk-config)
#+end_src

#+RESULTS:
#+begin_example
SKEL/MPK:MPK-CONFIG
  [symbol]

MPK-CONFIG names the standard-class #<STANDARD-CLASS SKEL/MPK:MPK-CONFIG>:
  Direct superclasses: AST, ID, CONFIG
  No subclasses.
  Not yet finalized.
  Direct slots:
    PATH
      Type: (OR PATHNAME NULL)
      Initargs: :PATH
    LOGGER
      Type: (OR NULL LOG:LOGGER-CONFIG)
      Initargs: :LOGGER
      Initform: (DEFAULT-LOGGER-CONFIG)
      Readers: LOGGER
      Writers: (SETF LOGGER)
    MPD
      Type: SKEL/MPK/MPD:MPD-CONFIG
      Initargs: :MPD
      Initform: (SKEL/MPK/MPD::LOAD-MPD-CONFIG)
    AUDIO
      Type: DSP/CORE:AUDIO-SYSTEM-CONFIG
      Initargs: :AUDIO
    VIDEO
      Type: DSP/CORE:VIDEO-SYSTEM-CONFIG
      Initargs: :VIDEO
    METRO
      Type: SKEL/MPK/METRO:METRO-CONFIG
      Initargs: :METRO
    DB
      Type: SKEL/MPK/DB:MPK-DB-CONFIG
      Initargs: :DB
    PICARD
      Type: CLI/TOOLS/MEDIA:PICARD-CONFIG
      Initargs: :PICARD
      Initform: (LOAD-PICARD-CONFIG)
    TRANSMISSION
      Type: CLI/TOOLS/NET::TRANSMISSION-CONFIG
      Initargs: :TRANSMISSION
      Initform: (CLI/TOOLS/NET::LOAD-TRANSMISSION-CONFIG)
    YTDL
      Initargs: :YTDL
      Initform: (CLI/TOOLS/NET::LOAD-YTDL-CONFIG)
#+end_example

* CLI
:PROPERTIES:
:ID:       096c8cf3-925a-4f03-b030-a3417ed8ea27
:CREATED:  <2025-07-08 Tue 16:41>
:END:
=mpk= provides a CLI application of the same name.
