#+title: organ
#+author: Richard Westhaver
#+setupfile: ../../../clean.theme
#+OPTIONS: num:nil

The =organ= CLI tool is used to manipulate [[https://orgmode.org/][Org Mode]] files.

* Overview
:PROPERTIES:
:ID:       ff9147a1-da33-46b1-b398-b87049e6c197
:END:
=Org-mode= the application depends on Emacs (it's written in Emacs
Lisp) but that doesn't mean we need to. To solve the issue of
interoperability between different systems, we are developing a tool
called [[https://lab.rwest.io/comp/core/-/tree/branch/default/lisp/lib/organ][organ]]. The purpose of =organ= is to provide an external API for
Org documents that doesn't depend on GNU Emacs.

If we were designing a /personal/ note-taking system, I would argue
that we don't need this tool. The problem is it's /not/ personal - we
have a much wider intended audience and need to present information in
many different ways. This means thinking about hundreds to thousands
of documents instead of tens, about processing those documents into a
full-text search database, and reducing cost along the way.

Emacs can do all of these things, but do you really want it to?

* help
:PROPERTIES:
:ID:       36603658-8f85-435c-b6b3-f8da47237f5c
:END:
#+begin_src shell :results pp replace :exports both
organ -h
#+end_src

#+RESULTS:
#+begin_example
organ v0.0.1 --- org-mode toolbox

  usage: organ [global] <command> [<arg>]

options:
  -l/--level* :  set the log level
  -h/--help* :  print help
  -v/--version* :  print version

commands:
  inspect : inspect an org file
  show : display local org info
  describe : describe local org info
  parse 
#+end_example
