#+title: ffi
#+author: Richard Westhaver
#+setupfile: ../../../clean.theme
#+OPTIONS: num:nil
This doc is about the [[https://en.wikipedia.org/wiki/Foreign_function_interface][Foreign Function Interface]] (FFI) features of the
=core=. 

Besides accessing system, OS, and external libraries via binding code
(dynamically in Lisp, statically in Rust), we also expose parts of the
core in a C-compatible fashion. In Lisp, we use the SB-ALIEN interface
to load (with dlopen) and call foreign symbols. In Rust we mostly use
rust-bindgen and the built-in rustc features.

* Libraries
:PROPERTIES:
:ID:       1eb797dc-d617-46cc-89e8-7b6103e526d2
:END:
The following binding libraries are provided with supporting
code. There is some cross-over between the Lisp and Rust bindings
depending on what library features we need and where. Some of the
bindings are very minimal or for experimental-use only only.
** xkb
:PROPERTIES:
:ID:       79b3a686-efe9-411e-9d1e-358113622949
:END:
These bindings are actually directed at libxkbcommon instead of
x11/xkb directly.
*** xkbcommon
:PROPERTIES:
:ID:       9b9be592-1314-4926-940a-908ff4844e29
:END:
https://xkbcommon.org/doc/current/md_doc_2quick-guide.html
** rocksdb
:PROPERTIES:
:ID:       5a1fd665-b72a-4d62-af4c-4967825f69c6
:END:
[[https://github.com/facebook/rocksdb/wiki][RocksDB Wiki]]
** btrfs
:PROPERTIES:
:ID:       6b3dc423-0e1c-458d-9f8e-bf7456f9a048
:END:
The kernel headers btrfs and btrfs_tree will be wrapped at some point
in addition to the userspace library (btrfsutil) documented below.
*** btrfsutil
:PROPERTIES:
:ID:       7296995d-2b67-45ec-94d9-8fe23126a602
:END:
https://github.com/kdave/btrfs-progs
** uring
:PROPERTIES:
:ID:       c0750228-7ba8-445a-8790-ca0310cf0a7d
:END:
https://man.archlinux.org/man/io_uring.7.en
** zstd
:PROPERTIES:
:ID:       6dbfed55-0d07-4090-bc3b-ea9317d9bfe5
:END:
zstd compression bindings: https://github.com/facebook/zstd
** tree-sitter
:PROPERTIES:
:ID:       8527c382-ae65-4ad9-8f70-9ff5c6b152f0
:END:
bindings to tree-sitter parser generator and language libraries: https://github.com/tree-sitter/tree-sitter
** COMMENT blake3
:PROPERTIES:
:ID:       a1807b79-9811-49f0-9524-cbf5e88c1a66
:END:
temporary package for CL implementation of Blake3 SHA. Wraps C
implementation (libblake3).
** COMMENT alpm
:PROPERTIES:
:ID:       cdd1682c-39b0-450e-a979-a5637cd15f43
:END:
https://man.archlinux.org/man/core/pacman/libalpm.3.en
https://github.com/archlinux/alpm.rs/tree/382af70cdbff8e1f65c0bf8df79693786f44429c/alpm/examples

** COMMENT bqn
:PROPERTIES:
:ID:       5014f979-5b3a-4dfc-89e3-5a5a23462a29
:END:
These bindings are for libcbqn which can be build from CBQN:
https://github.com/dzaima/CBQN
** COMMENT k
:PROPERTIES:
:ID:       47a60640-e387-4ac7-ab45-4f7a763e9611
:END:
https://codeberg.org/ngn/k
bindings for ngn/k (libk).
** COMMENT nuklear
:PROPERTIES:
:ID:       e1e942b2-ebe0-48e9-bdd3-f4e27b7fed7c
:END:
** COMMENT ssh2
:PROPERTIES:
:ID:       3c9e02d8-2c59-4ef5-8232-8422fd9e8ed3
:END:
