#+title: std
#+author: Richard Westhaver
#+description: The CC Standard Library
#+setupfile: ../../../clean.theme
#+OPTIONS: num:nil

This system is depended on by virtually all CC lisp software. It
contains our /standard/ extensions to the Lisp language and
implementation, SBCL.

The only exception is cl-ppcre which is an implicit dependency of
this system.

The /standard library/ itself is the set of symbols exported by the
*STD* package, which is a wrapper for the other /standard packages/.

These packages contain all the creature comforts a seasoned Lisper
needs. Some symbols are re-exported from the implementation internal
packages - SB-INT, SB-KERNEL, SB-C, SB-SYS, SB-UNICODE and
friends. Others are ported from long-standing community favorites (aka
'blessed' packages) such as ALEXANDRIA, SERAPEUM, CL-FAD, TRIVIAL-*,
etc.

We refrain from re-inventing the wheel as much as possible and in most
cases a dependency on STD may act as a drop-in replacement for
multiple blessed packages. We reference the original source code
repositories liberally in cases of pre-existing lisp systems, but you
can expect the code itself to be re-written according to our [[https://compiler.company/meta/style][style
guide]] and further enriched or optimized based on our own expectations.

#+BEGIN: lisp-system-info :system std :symbols nil
- packages
  #+CALL: lisp-system-packages[:post transpose]("std")

  #+RESULTS:

- dependencies
  #+CALL: lisp-system-dependencies[:post transpose]("std")

  #+RESULTS:

- dependents
  #+CALL: lisp-system-dependents[:post transpose]("std")

  #+RESULTS:

- files
  #+CALL: lisp-system-files[:post transpose]("std")

  #+RESULTS:

- tests
  #+CALL: lisp-system-tests[:post transpose]("std")

  #+RESULTS:

#+END

* Packages
:PROPERTIES:
:ID:       ad9abe97-311f-4e08-961e-7bd7e77fea90
:CREATED:  <2025-07-04 Fri 21:20>
:END:

All packages are prefixed with =std= followed by our standard
separator ~/~. This pattern is adhered to throughout our package /and/
system definitions.

All package definition files (~pkg.lisp~) have at least one primary or
'top-level' package (defined towards the end) preceded by any number
of sub-packages:

#+begin_src lisp :eval no
(defpackage :foo/bar (:use :cl) #+nil ... )
(defpackage :foo/baz (:use :cl :std) #+nil ... )
(defpackage :foo (:use :cl :foo/bar :foo/baz) #+nil ... )
#+end_src

** defpkg
:PROPERTIES:
:ID:       9d511180-0c52-48e8-aafe-fb48200659e4
:CREATED:  <2025-07-04 Fri 22:54>
:END:
You may notice in the standard library package definitions there is no
direct usage of the =defpackage= macro, or even =uiop:define-package=.
Instead, we rely on our own incarnation, =defpkg=:

#+begin_src lisp :results output
  (describe 'std/defpkg:defpkg)
#+end_src

#+RESULTS:
#+begin_example
STD/DEFPKG:DEFPKG
  [symbol]

DEFPKG names a macro:
  Lambda-list: (PACKAGE &REST CLAUSES)
  Documentation:
    Richard's Robust DEFPACKAGE macro. Based on UIOP:DEFINE-PACKAGE ymmv.
    
    DEFPKG takes a PACKAGE and a number of CLAUSES, of the form (KEYWORD . ARGS).
    
    DEFPKG supports the following standard extensions:
    USE, SHADOW, SHADOWING-IMPORT-FROM, IMPORT-FROM, EXPORT, INTERN -- as per CL:DEFPACKAGE.
    
    As well as the common extensions:
    RECYCLE, MIX, REEXPORT, UNINTERN -- as per UIOP/PACKAGE:DEFINE-PACKAGE
    
    Additionally, DEFPKG supports the following combinators:
    
    MIX-REEXPORT -- combination of MIX and REEXPORT
    
    USE-REEXPORT -- combination of USE and REEXPORT
    
    and the following custom extensions:
    
    PRELUDE -- treat the first element as the name of a 'prelude' package which
    will be defined with the remaining symbols re-exported from PACKAGE and only
    those symbols.
    
    In addition to defining and returning a package, when *DEFPKG-HOOK* is
    non-nil, it is called as a function with a single argument - the package being
    defined.
  Source file: /home/ellis/comp/core/std/defpkg.lisp
#+end_example

** sym
:PROPERTIES:
:ID:       d24943b2-5b49-47f5-901a-262a7d67d142
:CREATED:  <2025-07-04 Fri 23:31>
:END:
Symbols are quite important in Lisp and in the =std/sym= package you
will find some important utilities for working with them.

#+CALL: lisp-package-symbols[:post transpose]("STD/SYM")

#+RESULTS:

- =vboundp!= and =fboundp!= are inspired by the =c-mera= library and
  paper, providing quite useful for source-to-source compilers.
- =alias-function= and =alias-macro= are from the =lparallel= library,
  implemented in terms of =compiler-function= and =macro-function=
  respectively.
- =with-gensyms= is our preferred name as opposed to
  =with-unique-names= which is already defined by the
  implementation. Instead of re-writing we set the =macro-function= of
  the =with-gensyms= symbol directly.
- =symbolicate= and =keywordicate= are popular extensions defined by
  the implementation and re-exported here.

** list
:PROPERTIES:
:ID:       ee85a779-1af3-4e3d-a53c-0e89d498fec9
:CREATED:  <2025-07-04 Fri 23:51>
:END:
Lists are the most primitive as well as the most flexible sequence
type available in Lisp. At /run-time/ seasoned Lispers have a tendency
to use arrays instead of large lists when performance is needed, but
lists have some additional properties not shared by arrays which make
them the standard for all sorts of compile-time meta-programming. For
starters, lambda expressions, function calls, and all special forms
may be read and written as lists.

#+CALL: lisp-package-symbols[:post transpose]("STD/LIST")

#+RESULTS:

- =dlist= is an implementation of doubly-linked lists, originally
  inspired by =matlisp=. The vocabluarly includes =dcons=, =dpush=,
  =dpop=, =drdc=, =dcdr=, =dcar=, and =dappendf=.
- =toposort= is a variant on topological-sort also defined in
  =matlisp=.
- common functions, setf-accessors, and macros from =alexandria= and =serapeum=
- =merge!= and =sort!= from =cl-bench=
- list utils from Let over Lambda and On Lisp
** prim
:PROPERTIES:
:ID:       90934f06-13db-4920-97da-82a9144a4795
:CREATED:  <2025-07-04 Fri 23:51>
:END:
Some useful primitives which don't have a clear home package are
defined in =std/prim=.

#+CALL: lisp-package-symbols[:post transpose]("STD/PRIM")

#+RESULTS:

- =definline= is one of the most commonly used exports - as the name
  suggests it defines a function which is automatically declaimed
  ~inline~.

** condition
:PROPERTIES:
:ID:       0dfd5cbe-ce67-41e9-b622-85fdc18b62ee
:CREATED:  <2025-07-04 Fri 23:51>
:END:
Standard utilities for defining and handling conditions can be found
in =std/condition=.

#+CALL: lisp-package-symbols[:post transpose]("STD/CONDITION")

#+RESULTS:

** type
:PROPERTIES:
:ID:       69e652a0-29dc-4028-b3ac-5634be8603ce
:CREATED:  <2025-07-04 Fri 23:51>
:END:
=std/type= provides definitions for common types not covered in the
ANSI CL standard.

#+CALL: lisp-package-symbols[:post transpose]("STD/TYPE")

#+RESULTS:

** num
:PROPERTIES:
:ID:       86cbb20b-c72f-437b-873e-f2e7fdc966ec
:CREATED:  <2025-07-05 Sat 00:20>
:END:
Standard numeric utilities are provided by =std/num=. This package
spans multiple files covering specific features.

#+CALL: lisp-package-symbols[:post transpose]("STD/NUM")

#+RESULTS:

- utilities from =alexandria/numbers=
- number parsing functions: =parse-number=, =parse-integers=,
  =parse-real-number=, =parse-positive-real-number=
- floating-point encoding/decoding: =decode-float32=,
  =decode-float64=, =encode-float32=, and =encode-float64=
- u/leb128 encoding/decoding: =read-leb128=, =encode-leb128=,
  =encode-uleb128=, =decode-leb128=, and =decode-uleb128=

** stream
:PROPERTIES:
:ID:       1be1de57-d808-46aa-b1cb-ea7dc4920dcb
:CREATED:  <2025-07-05 Sat 00:26>
:END:

=std/stream= constains our standard set of stream definitions.

#+CALL: lisp-package-symbols[:post transpose]("STD/STREAM")

#+RESULTS:

- =wrapped-stream= implements the standard 'transparent' stream
  interface used as a superclass by other stream classes. The =stream=
  slot is accessible via the generic =stream-of=.

** array
:PROPERTIES:
:ID:       5076e7bd-b883-4bc4-95a2-04572e5a98a4
:CREATED:  <2025-07-05 Sat 00:26>
:END:

#+CALL: lisp-package-symbols[:post transpose]("STD/ARRAY")

#+RESULTS:

- implementation re-exports including =with-array-data=

** hash
:PROPERTIES:
:ID:       2c8b3513-b8df-4f74-8ff7-9c2a5d30a7a8
:CREATED:  <2025-07-05 Sat 00:26>
:END:
Hash-tables in Lisp are the O(1) older brother of alists and
plists. Sometimes it is convenient to use the cons-based siblings, but
for most instance of key -> value pairs you're better off with a
hash-table. =std/hash= provides some utilities for working with
them.

#+CALL: lisp-package-symbols[:post transpose]("STD/HASH")

#+RESULTS:

** curry
:PROPERTIES:
:ID:       95f7a622-fd3c-4561-acb0-d7c7198798f0
:CREATED:  <2025-07-05 Sat 00:26>
:END:
Currying is a popular paradigm in pure(r) functional programming
languages such as Haskell. =std/curry= provides such functional
composition primitives.

#+CALL: lisp-package-symbols[:post transpose]("STD/CURRY")

#+RESULTS:

** readtable
:PROPERTIES:
:ID:       e875124f-e09f-446a-a555-97771773113b
:CREATED:  <2025-07-05 Sat 00:38>
:END:

#+CALL: lisp-package-symbols[:post transpose]("STD/READTABLE")

#+RESULTS:

** macs
:PROPERTIES:
:ID:       86b3e95a-cc8b-49af-aedb-2610e12439df
:CREATED:  <2025-07-05 Sat 00:38>
:END:
Standard macros are defined in =std/macs=.

#+CALL: lisp-package-symbols[:post transpose]("STD/MACS")

#+RESULTS:

** sys
:PROPERTIES:
:ID:       9a91aff8-5aff-49c6-8c92-10b01f2b2af6
:CREATED:  <2025-07-05 Sat 00:39>
:END:

#+CALL: lisp-package-symbols[:post transpose]("STD/SYS")

#+RESULTS:

** bit
:PROPERTIES:
:ID:       a8728c46-b02d-4123-b397-3367e8e68263
:CREATED:  <2025-07-05 Sat 00:39>
:END:

#+CALL: lisp-package-symbols[:post transpose]("STD/BIT")

#+RESULTS:

** comp
:PROPERTIES:
:ID:       927003f3-97be-410d-b0c9-f981f2bbef10
:CREATED:  <2025-07-05 Sat 00:40>
:END:

#+CALL: lisp-package-symbols[:post transpose]("STD/COMP")

#+RESULTS:

** io
:PROPERTIES:
:ID:       668beb16-e294-4f86-8330-d6e6afbc551a
:CREATED:  <2025-07-05 Sat 00:40>
:END:

#+CALL: lisp-package-symbols[:post transpose]("STD/IO")

#+RESULTS:

#+begin_src lisp
  (generic-function-methods (function serialize))
#+end_src

#+RESULTS:
#+begin_example
(#<STANDARD-METHOD STD/IO:SERIALIZE (POD:CONTAINERFILE
                                     (EQL :BYTES)) {1201DBDE53}>
 #<STANDARD-METHOD STD/IO:SERIALIZE (POD:CONTAINERFILE
                                     (EQL :STRING)) {1201DBDE43}>
 #<STANDARD-METHOD STD/IO:SERIALIZE (ORGAN/GRAPH:ORG-GRAPH
                                     (EQL :JSON)) {1201DB9123}>
 #<STANDARD-METHOD STD/IO:SERIALIZE (ORGAN/GRAPH:ORG-GRAPH
                                     (EQL :DOT)) {1201DB9113}>
 #<STANDARD-METHOD STD/IO:SERIALIZE (ORGAN/GRAPH:ORG-GRAPH T) {12005FBA73}>
 #<STANDARD-METHOD STD/IO:SERIALIZE (COOKIE (EQL :STRING)) {1201B28AC3}>
 #<STANDARD-METHOD STD/IO:SERIALIZE (NET/CODEC/OSC::OSC-DATA
                                     (EQL :OSC)) {1201DA72D3}>
 #<STANDARD-METHOD STD/IO:SERIALIZE (TLV (EQL :STRING)) {1201DA72C3}>
 #<STANDARD-METHOD STD/IO:SERIALIZE (TLV (EQL :BYTES)) {1201DA72B3}>
 #<STANDARD-METHOD STD/IO:SERIALIZE (STRING (EQL :QRCODE)) {1200796D73}>
 #<STANDARD-METHOD STD/IO:SERIALIZE (INTEGER (EQL :BASE64)) {1200796613}>
 #<STANDARD-METHOD STD/IO:SERIALIZE (VECTOR (EQL :BASE64)) {1200212F63}>
 #<STANDARD-METHOD STD/IO:SERIALIZE (STRING (EQL :BASE64)) {1200796D53}>
 #<STANDARD-METHOD STD/IO:SERIALIZE (GIF-STREAM (EQL :GIF)) {1201D99C93}>
 #<STANDARD-METHOD STD/IO:SERIALIZE (TOML-TABLE (EQL :TOML)) {1201D8F9E3}>
 #<STANDARD-METHOD STD/IO:SERIALIZE (DAT/HTML::NODE T) {12005F6E93}>
 #<STANDARD-METHOD STD/IO:SERIALIZE (T (EQL :XML)) {12005F53C3}>
 #<STANDARD-METHOD STD/IO:SERIALIZE (T (EQL :JSON)) {12005F5313}>
 #<STANDARD-METHOD STD/IO:SERIALIZE (VECTOR (EQL :CSV)) {1200212F43}>
 #<STANDARD-METHOD STD/IO:SERIALIZE (GRAPH (EQL :DOT)) {1201D6F7E3}>
 #<STANDARD-METHOD STD/IO:SERIALIZE (JPEG:JPEG-COMPRESSOR
                                     (EQL :JPEG)) {1201D89163}>
 #<STANDARD-METHOD STD/IO:SERIALIZE (T (EQL :URL)) {12005F2743}>)
#+end_example

#+begin_src lisp
  (generic-function-methods (function deserialize))
#+end_src

#+RESULTS:
#+begin_example
(#<STANDARD-METHOD STD/IO:DESERIALIZE (PATHNAME (EQL :PKGBUILD)) {1200A01EF3}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (PATHNAME
                                       (EQL :CONTAINERFILE)) {1200A01E63}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (T (EQL :OPENAPI)) {12005FA773}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (JSON-OBJECT
                                       (EQL :OPENAPI)) {1201CF5493}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (STREAM (EQL :DBUS)) {1200ECC7A3}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (VECTOR (EQL :OSC)) {1200212F83}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (STREAM (EQL :TLV)) {1200ECC793}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (SIMPLE-ARRAY (EQL :TLV)) {1200212893}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (PATHNAME
                                       (EQL :SYSTEMD-UNIT)) {1200A01DD3}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (T (EQL :PACMAN-CONFIG)) {12005F98E3}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (STRING (EQL :AUTHINFO)) {1200796DA3}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (PATHNAME (EQL :AUTHINFO)) {1200A01DC3}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (STREAM (EQL :BASE64)) {1200ECC773}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (STRING (EQL :BASE64)) {1200796D63}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (STRING (EQL :BIB)) {1200796D03}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (PATHNAME (EQL :BIB)) {1200A01DA3}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (STREAM (EQL :BIB)) {1200ECC763}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (STREAM (EQL :TOML)) {1200ECC753}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (STRING (EQL :TOML)) {1200796CE3}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (PATHNAME (EQL :TOML)) {1200A01D83}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (T (EQL :DESKTOP-ENTRY)) {12005F7093}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (PATHNAME (EQL :INI)) {1200A01D73}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (STRING (EQL :INI)) {1200796CD3}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (STREAM (EQL :INI)) {1200ECC743}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (T (EQL :HTML)) {12005F6E83}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (STRING (EQL :SVG)) {1200796CB3}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (PATHNAME (EQL :SVG)) {1200A01D53}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (PATHNAME (EQL :XML)) {1200A01D43}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (STREAM (EQL :XML)) {1200ECC733}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (STRING (EQL :XML)) {1200796CA3}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (T (EQL :JSON-SCHEMA)) {12005F5323}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (JSON-OBJECT
                                       (EQL :JSON-SCHEMA)) {1201CF54A3}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (STREAM (EQL :JSON)) {1200ECC723}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (PATHNAME (EQL :JSON)) {1200A01D23}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (STRING (EQL :JSON)) {1200796C73}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (STRING (EQL :CSV)) {1200796C63}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (T (EQL :CSV)) {12005F52F3}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (PATHNAME (EQL :CSV)) {1200A01D13}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (STRING (EQL :DOT)) {1200796C53}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (T (EQL :ASN1)) {12005F52E3}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (T (EQL :JPEG)) {12005F5183}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (JPEG:JPEG-DECOMPRESSOR
                                       (EQL :JPEG)) {1201CF54B3}>
 #<STANDARD-METHOD STD/IO:DESERIALIZE (T (EQL :URL)) {12005F2753}>)
#+end_example

** alien
:PROPERTIES:
:ID:       068b1f42-116a-413c-b46b-4ae46a7ba103
:CREATED:  <2025-07-05 Sat 00:40>
:END:

#+CALL: lisp-package-symbols[:post transpose]("STD/ALIEN")

#+RESULTS:

** meta
:PROPERTIES:
:ID:       2510bbba-5b16-47bb-a608-5a967e6b9c93
:CREATED:  <2025-07-05 Sat 00:41>
:END:

#+CALL: lisp-package-symbols[:post transpose]("STD/META")

#+RESULTS:

** seq
:PROPERTIES:
:ID:       45c6bddc-6978-43ca-bfd3-e6d49b8b4092
:CREATED:  <2025-07-05 Sat 00:41>
:END:

#+CALL: lisp-package-symbols[:post transpose]("STD/SEQ")

#+RESULTS:

** thread
:PROPERTIES:
:ID:       fc427e9b-83f8-4c84-9d88-aa8f0abf9068
:CREATED:  <2025-07-05 Sat 00:41>
:END:

#+CALL: lisp-package-symbols[:post transpose]("STD/THREAD")

#+RESULTS:

** task
:PROPERTIES:
:ID:       72e469e2-e3b7-4820-9c3d-4a5e106ae75a
:CREATED:  <2025-07-05 Sat 00:41>
:END:

#+CALL: lisp-package-symbols[:post transpose]("STD/TASK")

#+RESULTS:

** async
:PROPERTIES:
:ID:       4eb79c5a-bf3a-41a4-998f-0e573ff21d1d
:CREATED:  <2025-07-05 Sat 00:42>
:END:

#+CALL: lisp-package-symbols[:post transpose]("STD/ASYNC")

#+RESULTS:

** rand
:PROPERTIES:
:ID:       83338606-d05f-40bc-82e8-865641975b71
:CREATED:  <2025-07-05 Sat 00:42>
:END:

#+CALL: lisp-package-symbols[:post transpose]("STD/RAND")

#+RESULTS:

** print
:PROPERTIES:
:ID:       9b6ff571-ca5c-4fc2-9a4a-ab8803def3bf
:CREATED:  <2025-07-05 Sat 00:42>
:END:
=std/print= contains a variety of format and print-related functions,
including basic text drawing primitives.

#+begin_src lisp :package :std/print :results output
  (smile)
#+end_src

#+RESULTS:
:  ▄▀▀▀▀▄ 
: █ ▀  ▀ █
: █ ▀▄▄▀ █
:  ▀▄▄▄▄▀ 

#+CALL: lisp-package-symbols[:post transpose]("STD/PRINT")

#+RESULTS:

Some examples are shown below:

#+begin_src lisp :results output
  (print-in-box "hello world")
#+end_src

#+RESULTS:
: ┌───────────┐
: │hello world│
: └───────────┘

#+begin_src lisp :results output
  (print-slots (make-spin-queue))
#+end_src

#+RESULTS:
: 
: HEAD                           = (:NULL)
: TAIL                           = (:NULL)

#+begin_src lisp :results output
  (print-heading "table formatter")
  (print-table (group (iota 200) 10) :align :right :gap " ")
  (print-heading "tree formatter")
  (fmt-tree t (group (zip-list (group (iota 42) 3)) 2))
#+end_src

#+RESULTS:
#+begin_example

table formatter
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

  0   1   2   3   4   5   6   7   8   9
 10  11  12  13  14  15  16  17  18  19
 20  21  22  23  24  25  26  27  28  29
 30  31  32  33  34  35  36  37  38  39
 40  41  42  43  44  45  46  47  48  49
 50  51  52  53  54  55  56  57  58  59
 60  61  62  63  64  65  66  67  68  69
 70  71  72  73  74  75  76  77  78  79
 80  81  82  83  84  85  86  87  88  89
 90  91  92  93  94  95  96  97  98  99
100 101 102 103 104 105 106 107 108 109
110 111 112 113 114 115 116 117 118 119
120 121 122 123 124 125 126 127 128 129
130 131 132 133 134 135 136 137 138 139
140 141 142 143 144 145 146 147 148 149
150 151 152 153 154 155 156 157 158 159
160 161 162 163 164 165 166 167 168 169
170 171 172 173 174 175 176 177 178 179
180 181 182 183 184 185 186 187 188 189
190 191 192 193 194 195 196 197 198 199

tree formatter
▀▀▀▀▀▀▀▀▀▀▀▀▀▀

 ╭─ ((18 19 20))
 │   ╰─ (21 22 23)
 ├─ ((12 13 14))
 │   ╰─ (15 16 17)
 ├─ ((6 7 8))
 │   ╰─ (9 10 11)
(((0 1 2)) ((3 4 5)))
 ├─ ((24 25 26))
 │   ╰─ (27 28 29)
 ├─ ((30 31 32))
 │   ╰─ (33 34 35)
 ╰─ ((36 37 38))
     ╰─ (39 40 41)
#+end_example

#+begin_src lisp :results output
  (draw-one-in-chance 3)
  (draw-chance 87)
  (plot-function 'sin -5 5)
#+end_src

#+RESULTS:
#+begin_example
▀ █ ▀▀ ▄  ▀▀▄▀  ▀▀▀▀▄▀  ▄▄▄▄ █▀ 
▀ ▄ ▀▄▄ ▀█ ▄▄▄▄ ▄ ▄█ ▀▄▀▀ ▄█▀▄██
▄▀▀ ▀▄█▀▄ ▀▄▄██▀ ▀█▄██▀▄█▀▀ ▄▄  
 ▀        ▄ █▄▀█▀▀    ▀ ▀█  █▄▀█
 ▄█▄▄   █  █▀ ▄▀█▀  ▀█  ▀▀  █ ▄ 
▄▀ ▀█▀▄▄  ▀    ▄    █   ▄▄  ▄█▄▀
▀▀▄ ▄▄ ▄ ▀▄▀█ ▄█  ▀  ▀▀    ▄ ▀▄ 
 █  ▄ █   █▀   ▀▄▀██ ▀▄      █ █
 ▄▀█  ▄ ▄█▀▀▄▀  ▀▀█▄▀▀ ▀ ▄▄▀ ▀█ 
 ▀  ▄▄ ▀  ▀  ▄▄▀  ▄    ▄ ▀▄▀▀ █ 
 ▄█   ▄▄ ▄▀█ ▄ ▄█  █▄     █▀▀▄▄▄
  ▀  ▀▄ ▄██▄▄ █ █ ▀▀     █ █ ▀▄ 
  ▄   ▀ ▀▀▀   █  ▀▀█  ▀ ▄█▄▀▀   
 ▀▀ ▀█  ▄▄ ▀▄▀█   ▄▄█▀▀ ▀ ▀ ▄  ▄
▄  ▄   ▄▄ ▀   ▄ ▄█  █ ▄▄  ▀▀▀▄█▀
 ▄ ▀▀ ▄██▀▄  ▀██ ▀▀▀ ▄▄▄▀▄▄ ▄▄ ▀
███████▀▄█ ███████▄▀█▄ ██▀▄▄▀ █ ▀█ █▀▄█▀█  ▄▀▄▄▄▄▄ █   ▀ ▄▄ ▄▀▄         ▀▄▀  ▄         
██████████████▄▄█▄▄██▄█▀█▀█▀▀▄█████ ▄ ▀ ██▄ ▄█▄▄ ▀█  ▀ ███▄▀ ▄▀▄▄▀ ▄  ▀ ▄  ▄           
█████████▄▀▀▀ ██▄▄▄██ ▄▄██▀▄█▄▄█▀▄█▄██   ██ ▄█▀ ▀ █▄▀▀▄█  ▄█ █▄▄ ▄  ▀ ▀ █ ▀            
██████▀█████▀██▀▀███▄█▀▀█████▄█▀  ▄▀▀▄█▀█ █▀▀▄  ▄▀▀█  ▀▄     ▄      ▀      ▀           
████████▄█████▀██▄▄▄▀███▄████▄▄▀▀▀▄▀ ▄█ ▄ █ ▀▄██ ▀█ ▀ ▀ ▀█ ▄     ▄▄█ ▄ █ ▀             
███████████▀█▀▀█████▄█▀█▄█▀▄▄██▀██▄█  ▀▄ █▄▀▄█▄▀▄    ▄ ▀█▀██▄▄▄▀ ▀ ▄▀▀▀   ▄█  ▄▀       
▀█████▀▀█▄██▄▀███▀██▄▀█▄█▄▀███▄▀▄ ▀ █▄▀█▀ ▀█▀▄▄▀▄▄▀    ▀  ▀   ▀▄ █ ▄    ▀▀    ▀        
█████▄████▄▄███▀█▀▀▄███▄█ ▄▄ ██▄ ▄▄█▄█▀▀██▀▄ ▄▄▄▄█▀ ▀ ▄▄▄   ▄▄▄  ▄▄ ▄ ▄      █         
██████████▀██ ▀█▄▀██▄▄█▀██▀████▀ ███ ▄ ▀  ▄ █▄▄ ▀  █▄ ▀   █▀ ▄ ▀ ▄ ▄▀  ▀▄▀     ▄       
█████████▄████▄█▀█▀█████ █▀▄▄▄█▀▀ ██▀█ ▀▀█▀   ▄ ▀▄ ▄ ▄▀▀ █▀ ▀█▄   ▄▀   ▄▀   ▄▄         
███████▄██▀████▄█▄█▀█▄███▄█▀ █  ▄▄▄█▄▄▄███▀▀▀ ▄▄▄  █▀█▀██▀█▄                ▀▄         
████▀██████▀██▀████▀▄ ██████▄██ █ ████ █▀▄▀ ▀▄▀  ██ █ ▀█▄  ▀          ▀        ▀       
████████▀██████▄▀▄█▀██▀██▀▀█ █▄██▀▄▄▀▄██▄▀▄  ▄ ▄██▀  ▄▄ ▀▄ █▄    ▀     ▄   ▀ ▄   ▄     
██████████▄█▄███ █▀▀▄███▀█▀▄▀█▀██▄▄▀▄▄    ███▀▄ ▄▀    █▄ ▄▀    █    █ ▄    ▄       ▄   
██████████████ ██▄███▀▀▄█▄█ ██ ▄██ █▄▄▄█▀  ▀ ██▄▄▀▀  ▀█ ▄▄ █ ▄    ▀ ▀ ▀                
█████████▄█ ▄███ ▄██████▄▀▀█▀█▄ ▀▀▄▀▀▀▄ ██  █▀██▀▀ ▀▄█▄  ▄▄▄ ▀        ▀▄     ▄         
█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█
█                                                              █
█                                                              █
█                                                              █
█                                                              █
█▀▀▀▀▄▄                               ▄▄▀▀▀▀▀▄▄                █
█      ▀▄                           ▄▀         ▀▄              █
█        ▀▄                       ▄▀             ▀▀▄           █
█          ▀▄                  ▄▀▀                  ▀▄         █
█            ▀▄▄             ▄▀                       ▀▄       █
█               ▀▄         ▄▀                           ▀▄     █
█                 ▀▀▄▄▄▄▄▀▀                               ▀▀▄▄▄█
█                                                              █
█                                                              █
█                                                              █
█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█
#+end_example

#+begin_src lisp
  (human-readable-size 101010101) ;; in btes
#+end_src

#+RESULTS:
: 96.33 MB

#+begin_src lisp :results output
  (print-heading "ascii art")
  (sun :size 24)
  (peace)
  (sunbeam :step 4 :size 32)
  (moire :size 32 :filled t :step 2)
#+end_src

#+RESULTS:
#+begin_example

ascii art
▀▀▀▀▀▀▀▀▀

         ▄▄▄▄▄▄▄        
      ▄███████████▄     
    █████████████████   
  ▄███████████████████▄ 
 ▄█████████████████████▄
 ███████████████████████
 ███████████████████████
 ███████████████████████
  █████████████████████ 
   ▀█████████████████▀  
    ▀▀█████████████▀▀   
       ▀▀███████▀▀      
    ▄▄▄▄▄   
  ▄▀  █  ▀▄ 
 █    █    █
 █   ▄█▄   █
 ▀▄▄▀ █ ▀▄▄▀
   ▀▄▄█▄▄▀  
█  ▄▀  ▄▀  ▄▀  ▄▀  ▄▀  ▄▀  ▄▀ ▄▀
█  █   █  ▄▀  █   █  ▄▀  ▄▀ ▄▀  
█  █  █   █  █  ▄▀  █  ▄▀ ▄▀ ▄▀▀
█  █  █  █  █  ▄▀ ▄▀ ▄▀ ▄▀ ▄▀   
█ █  █  █  █  █  █ ▄▀ ▄▀ ▄▀  ▄▀▀
█ █  █ ▄▀ █ ▄▀ ▄▀ █ ▄▀▄▀▀ ▄▀▀   
█ █ █ ▄▀ █ ▄▀▄▀ ▄▀▄▀▄▀ ▄▄▀  ▄▄▀▀
█ █ █ █ █ █ ▄▀▄▀▄▀▄▀ ▄▀  ▄▄▀    
██ █ █ █ █▄▀▄▀▄█▄▀▄▀▀ ▄▀▀  ▄▄▀▀▀
██ █▄▀█▄▀▄█▀▄█▀▄▄▀▄▄▀▀ ▄▄▀▀     
███▄▀█▄█▀█▄█▀▄▀▄▄▀ ▄▄▀▀   ▄▄▄▀▀▀
███████▄███▀█▄▀▄▄▀▀ ▄▄▄▀▀▀      
██████████▀█▄▀▀▄▄▀▀▀   ▄▄▄▄▀▀▀▀▀
███████████▄▀▀█▄▄▄▀▀▀▀▀         
█████████▀▀███▄▄▄▄▄▄▄▀▀▀▀▀▀▀▀▀▀▀
███████████▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄ 
          ▄▄▄▀▀▀▀▀▀▀▄▄▄   ▄▄▄▀▀▀▀▀▀▀▄▄▄         
       ▄▀▀▄▄▄▀▀▀▀▀▀▀▄▄▄█▀█▄▄▄▀▀▀▀▀▀▀▄▄▄▀▀▄      
    ▄▀▀▄▄▀ ▄▄▀▀▀▀▀▀▀▄█▀█▄█▀█▄▀▀▀▀▀▀▀▄▄ ▀▄▄▀▀▄   
   ▄▀▄▀ ▄▀▀▄▄▀▀▀▀▀▀██▄▀▀▄▀▀▄██▀▀▀▀▀▀▄▄▀▀▄ ▀▄▀▄  
  █ ▄▀▄▀ ▄▀ ▄▄▀▀▀▀█▄▄▀██ ██▀▄▄█▀▀▀▀▄▄ ▀▄ ▀▄▀▄ █ 
 █ █ ▄▀▄▀ ▄▀ ▄▀▀▀█▀█ ██▄▀▄██ █▀█▀▀▀▄ ▀▄ ▀▄▀▄ █ █
▄▀▄▀▄▀▄▀ █ ▄▀▄▄▀█▀▄███▄█ █▄███▄█▀▀▄▄▀▄ █ ▀▄█▄▀▄█
█ █ █ █ █ █ ▄▀▄▀█▀███ ███ ███▀██▀▀▄█▄ ███ ███ ██
█ █ █ █ █ █ █ █ █ ███ ███ ███ ██  ███ ███ ███ ██
█ █ █ █ ▀▄▀▄ █▄▀█▀███▄██▀▄██████▀▀▄█ ▄▀█▀ ███ ██
 █ █ █ █ ▀▄ ▀▄ ▀▀█ █▀█▄█ █▄█▀█ █▀▀ ▄▀ ▄▀ █ █ █ █
 ▀▄▀▄ █ ▀▄ ▀▄▄▀▀▀▀██▄▀█▄▀▄█▀▄██▀▀▀▀▄▄▀ ▄▀ █ ▄▀▄▀
  ▀▄ █ ▀▄ ▀▄▄ ▀▀▀▀▀▄▄█▀▀▄▀▀█▄▄▀▀▀▀▀ ▄▄▀ ▄▀ █ ▄▀ 
    █ ▀▄▄▀▀▄▄▀▀▀▀▀▀▀█▄▀█▄█▀▄█▀▀▀▀▀▀▀▄▄▀▀▄▄▀ █   
     ▀▀▄ ▀▄▄▄▀▀▀▀▀▀▀▄███ ███▄▀▀▀▀▀▀▀▄▄▄▀ ▄▀▀    
        ▀▀▄▄▄▀▀▀▀▀▀▀▄▄▄▀▀▀▄▄▄▀▀▀▀▀▀▀▄▄▄▀▀       
#+end_example

** path
:PROPERTIES:
:ID:       cb62d9b7-2db8-4d51-8a90-d29d965a6bd2
:CREATED:  <2025-07-05 Sat 00:42>
:END:

#+CALL: lisp-package-symbols[:post transpose]("STD/PATH")

#+RESULTS:

** file
:PROPERTIES:
:ID:       aa4ddff0-f92d-4c47-ba0d-25f141c8e582
:CREATED:  <2025-07-05 Sat 00:42>
:END:

#+CALL: lisp-package-symbols[:post transpose]("STD/FILE")

#+RESULTS:

** os
:PROPERTIES:
:ID:       448fcb7e-5d70-47e0-9dba-64269c715641
:CREATED:  <2025-07-05 Sat 00:42>
:END:

#+CALL: lisp-package-symbols[:post transpose]("STD/OS")

#+RESULTS:

** pipe
:PROPERTIES:
:ID:       c1bd85b5-d13b-4d0e-ae5a-38ef97a8ea17
:CREATED:  <2025-07-05 Sat 00:43>
:END:

#+CALL: lisp-package-symbols[:post transpose]("STD/PIPE")

#+RESULTS:

** string
:PROPERTIES:
:ID:       f41ce152-7e10-4648-98ae-7c0a10b293af
:CREATED:  <2025-07-05 Sat 00:43>
:END:

#+CALL: lisp-package-symbols[:post transpose]("STD/STRING")

#+RESULTS:

** WIP defsys
:PROPERTIES:
:ID:       9831687d-15bd-4b60-ae0d-bcf4cd8b45bf
:CREATED:  <2025-07-04 Fri 23:20>
:END:
#+call:lisp-package-dependencies("STD/DEFSYS") :post transpose

#+RESULTS:

#+call:lisp-package-files("STD/DEFSYS")

#+RESULTS:
| /home/ellis/comp/core/skel/core/project.lisp | /home/ellis/comp/core/skel/core/component.lisp | /home/ellis/comp/core/std/defsys.lisp |

#+call:lisp-package-symbols("STD/DEFSYS") :post transpose

#+RESULTS:

#+call:file-description("~/comp/core/std/defsys.lisp")

#+RESULTS:
: The Core System Definition facility.

#+call:file-commentary("~/comp/core/std/defsys.lisp")

#+RESULTS:
#+begin_example
replacement/wrapper for ASDF

goals:
- dynamic asdf compatibility
- replace quicklisp (will need to be in skel)
- share resources between system and dependency manager
- integrate with skel/packy (package distributor)
- async ready
- parallel compilation
- LISP ONLY -- multi-lang systems are handled by skel
notes:

operations we care about:
- read
- load
- compile
#+end_example

The =std/defsys= package is the last package defined in the =std=
system, it provides a DEFSYS macro which is our equivalent to the more
popular =ASDF:DEFSYSTEM=.

Once the =std/defsys= package is loaded the /general preference/
across the =core= is to use =STD/DEFSYS= (nickname is =SYS=) instead
of =ASDF=, although both are generally supported.

Defsys is designed in such a way as to be directly integrated with the
host Lisp compiler. System definitions (=SYS:DEFSYS= forms) may be
compiled to a FASL just like any other lisp file. Typically the file
type is changed to =".fsys"= to distinguish them from standard lisp
fasls - see the =SYS:COMPILE-SYS= function for details.

*** ASDF Compatibility
:PROPERTIES:
:ID:       5dfc7fea-c82d-4c46-8b38-26f244cc24f4
:CREATED:  <2025-12-10 Wed 20:42>
:END:
all =SYS:COMPONENT= classes have relevant =CHANGE-CLASS= methods
defined for their relevant ASDF counterparts so that you can translate
between the two when needed, but in general this is not needed.

Many SYS methods accept an ASDF keyword which defaults to the value of
=*ASDF-COMPATIBILITY*=. When Non-nil, 

#+call: describe-lisp-symbol('*asdf-compatibility*)

#+RESULTS:
: STD/DEFSYS:*ASDF-COMPATIBILITY*
:   [symbol]
: 
: *ASDF-COMPATIBILITY* names a special variable:
:   Value: NIL
:   Documentation:
:     When non-nil, enable compatibility between STD/DEFSYS and SYSTTEM - component
:     operations will use ASDF and DEFSYS will first pass all argument to
:     ASDF:DEFSYSTEM.
